Repository adempiere/adempiere-vue, pull requests merged in 2019-12, with the labels that each got.

#188 fix: Corrects update records, no value was sent.
  src/store/modules/ADempiere/panel.js
  src/store/modules/ADempiere/windowControl.js
Labels: Base Changes

#168 Add Export Window Record
  src/components/ADempiere/ContextMenu/contextMenuDesktop.vue
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/DataTable/contextMenu.vue
  src/components/ADempiere/DataTable/index.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/processControl.js
  src/store/modules/ADempiere/utils.js
  src/store/modules/ADempiere/windowControl.js
  src/utils/ADempiere/exportUtil.js
Labels: UI Base Features, Waiting for User Changes

#174 Support to private access feature
  src/api/ADempiere/data.js
  src/api/user.js
  src/components/ADempiere/ContextMenu/contextMenuDesktop.vue
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/Panel/index.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/data.js
  src/store/modules/ADempiere/panel.js
  src/store/modules/ADempiere/processControl.js
  src/store/modules/ADempiere/window.js
  src/store/modules/user.js
  src/views/ADempiere/Window/index.vue
Labels: UI Base Features, Waiting for User Changes

#193 Change breadcrumb menu options trigger
  src/components/Breadcrumb/index.vue
Labels: UI Base Features

#191 Unify popovers with field info an zoom in
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/Panel/index.vue
  src/store/modules/ADempiere/panel.js
Labels: UI Base Features, Waiting for User Changes

#195 Add validation for private access records
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
Labels: Base Changes

#198 Redefine API to provider enrollment.
  src/api/ADempiere/enrollment.js
  src/store/modules/ADempiere/enrollment.js
Labels: Base Changes

#199 Redefine API to provider access.
  src/api/user.js
  src/router/modules/ADempiere/menu.js
  src/store/modules/ADempiere/context.js
  src/store/modules/user.js
  src/utils/ADempiere/dictionaryUtils.js
  src/utils/ADempiere/index.js
  src/utils/ADempiere/valueUtils.js
  src/views/login/index.vue
Labels: Base Changes

#200 Add support to api version for:
  package.json
Labels: Base Changes, Update Library

#186 feat: Add support to sequence tab.
  package.json
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/ContextMenu/index.vue
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/Dialog/index.vue
  src/components/ADempiere/Panel/index.vue
  src/components/ADempiere/SequenceOrder/index.vue
  src/components/ADempiere/Tab/index.vue
  src/components/ADempiere/Tab/tabChildren.vue
  src/components/ADempiere/Tab/tabMixin.js
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/data.js
  src/store/modules/ADempiere/panel.js
  src/store/modules/ADempiere/processControl.js
  src/store/modules/ADempiere/window.js
  src/store/modules/ADempiere/windowControl.js
  src/utils/ADempiere/dictionaryUtils.js
  src/views/ADempiere/Browser/index.vue
  src/views/ADempiere/Process/index.vue
  src/views/ADempiere/Window/index.vue
Labels: UI Base Features, Waiting for User Changes

#202 fix: Correction of the date field type range when clearing the value.
  src/components/ADempiere/Field/FieldDate.vue
  src/components/ADempiere/Field/FieldMixin.js
Labels: Base Changes, Waiting for User Changes, bug

#203 Update version for Client library 1.8.2
  package.json
Labels: Base Changes, Update Library

#206 Remove bad implementation for dashboard
  src/components/ADempiere/Favorites/index.vue
  src/components/ADempiere/PendingDocuments/index.vue
  src/components/ADempiere/RecentItems/index.vue
  src/store/modules/ADempiere/dashboard.js
Labels: Base Changes, UI Base Features

#204 Suppot to Lookups
  src/components/ADempiere/Field/FieldSelect.vue
Labels: Base Changes

#205 Bugfix call user uuid from user info
  src/store/modules/user.js
Labels: Base Changes

#201 #171 bugfix show record from zoom action
  src/store/modules/ADempiere/panel.js
Labels: Base Changes

#207 fix: Error render lookups fields without reference.
  src/components/ADempiere/Field/FieldSelect.vue
  src/store/modules/ADempiere/lookup.js
Labels: Base Changes, UI Lookups

#210 fix: Correct process metadata loading in modal.
  src/api/ADempiere/dictionary.js
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/browser.js
  src/store/modules/ADempiere/panel.js
  src/store/modules/ADempiere/processControl.js
  src/store/modules/ADempiere/window.js
  src/utils/ADempiere/dictionaryUtils.js
Labels: Base Changes, bug

#209 Add support to zoom from smart browser
  src/components/ADempiere/DataTable/index.vue
  src/store/modules/ADempiere/panel.js
  src/utils/ADempiere/valueUtils.js
Labels: Base Changes, UI Base Features

#211 Increase version
  package.json
Labels: Update Library
