Repository adempiere/adempiere-vue, pull requests merged in 2019-11, with the labels that each got.

#159 Add Export to Smart Browser
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
Labels: UI Base Features

#160 feat: Add text long editor to Markdown.
  src/components/ADempiere/Field/FieldNumber.vue
  src/components/ADempiere/Field/FieldText.vue
  src/components/ADempiere/Field/FieldTextLong.vue
  src/components/ADempiere/Field/fieldSize.js
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/Field/references.js
Labels: UI Base Features, UI Lookups

#161 Add new template to Field Text Long.
  src/components/ADempiere/Field/FieldTextLong.vue
Labels: UI Base Features, UI Lookups

#166 Set default templates for github issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: Base Changes, enhancement

#173 fix: #172 Reload a window with a record, loses the display column.
  src/components/ADempiere/Field/FieldSelect.vue
  src/store/modules/ADempiere/panel.js
Labels: Base Changes, bug

#177 fix: Correct rank type numerical fields.
  src/components/ADempiere/Field/FieldNumber.vue
  src/store/modules/ADempiere/browser.js
  src/store/modules/ADempiere/panel.js
  src/store/modules/ADempiere/process.js
  src/utils/ADempiere/index.js
Labels: UI Base Features

#175 Bugfix references filtering
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/ContextMenu/items.vue
  src/components/ADempiere/Panel/index.vue
  src/store/modules/ADempiere/windowControl.js
Labels: Base Changes

#179 Update Client version for gRPC
  package.json
Labels: Base Changes

#180 Change business data version to 1.7.8
  package.json
Labels: Update Library

#162 add feature print format selection in report viewer
  src/api/ADempiere/data.js
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/data.js
  src/store/modules/ADempiere/processControl.js
  src/views/ADempiere/ReportViewer/index.vue
Labels: UI Base Features, Waiting for User Changes

#165 add feature report view selection in report viewer
  src/api/ADempiere/data.js
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/processControl.js
  src/views/ADempiere/ReportViewer/index.vue
Labels: Base Changes, Waiting for User Changes

#181 feat: Add show totals to Smart Browser.
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/Field/FieldNumber.vue
Labels: UI Base Features

#163 Add feature print format setup action
  src/components/ADempiere/ContextMenu/contextMenuDesktop.vue
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/ContextMenu/items.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/utils/ADempiere/zoomWindow.js
Labels: UI Base Features, Waiting for User Changes

#171 Add support to zoom action in fields
  src/components/ADempiere/Field/index.vue
Labels: UI Base Features, Waiting for User Changes

#185 Add support to 1.8.0 version of data
  package.json
Labels: Update Library

#187 feat: Add totals with selection.
  src/components/ADempiere/DataTable/index.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/browser.js
  src/store/modules/ADempiere/panel.js
  src/store/modules/ADempiere/window.js
Labels: UI Base Features
