Repository adempiere/adempiere-vue, pull requests merged in 2020-04, with the labels that each got.

#424 error requests when advanced query
  src/components/ADempiere/Panel/index.vue
  src/store/modules/ADempiere/utils.js
  src/store/modules/ADempiere/windowControl.js
  src/views/ADempiere/Window/index.vue
Labels: bug

#426 improves: Optimize the times data is consulted in the vuex store
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/ContextMenu/index.vue
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/Panel/index.vue
  src/components/ADempiere/Tab/index.vue
  src/components/ADempiere/Tab/tabMixin.js
  src/store/modules/ADempiere/panel.js
  src/store/modules/ADempiere/window.js
  src/store/modules/ADempiere/windowControl.js
  src/utils/ADempiere/dictionaryUtils.js
  src/views/ADempiere/Window/index.vue
Labels: Base Changes, Improve Source Code

#427 fix: Context menu relations in report view.
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/store/modules/ADempiere/processControl.js
Labels: bug

#428 Change pull request template by a little text
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Improve Source Code

#429 Remove default table C_Order hardcoded from list workdlows
  src/store/modules/ADempiere/contextMenu.js
Labels: Improve Source Code

#430 Fixed error with call service for list document statuses when a recor…
  src/components/ADempiere/Panel/index.vue
Labels: bug

#431 Fixed error with parameter name for workflow process used for documen…
  src/components/ADempiere/WorkflowStatusBar/index.vue
Labels: Base Changes, bug

#432 Remove unnecessary parameters for pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#433 fix: Without records refreshing on different child tab than the first.
  src/components/ADempiere/Tab/index.vue
  src/components/ADempiere/Tab/tabChildren.vue
  src/components/ADempiere/Tab/tabMixin.js
Labels: Base Changes, bug

#434 Upgrade version for gRPC data, this is a critical change for transfer…
  package.json
Labels: Update Library

#435 fix: Lookup with -1 as default value.
  src/components/ADempiere/Field/FieldSelect.vue
  src/store/modules/ADempiere/lookup.js
Labels: UI Custom Lookups, bug

#436 fix: Without title in some view's component.
  src/views/ADempiere/Browser/index.vue
  src/views/ADempiere/Process/index.vue
  src/views/ADempiere/ReportViewer/index.vue
Labels: Base Changes

#437 fix: Refresh window records should not run callout.
  src/store/modules/ADempiere/windowControl.js
Labels: Base Changes, UI Base Features

#342 fix #341 Send double values with 0 values in decimals
  package.json
  src/api/ADempiere/data.js
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/Field/FieldNumber.vue
  src/components/ADempiere/Field/references.js
  src/main.js
  src/store/modules/ADempiere/calloutControl.js
  src/store/modules/ADempiere/data.js
  src/store/modules/ADempiere/panel.js
  src/store/modules/ADempiere/windowControl.js
  src/utils/ADempiere/dictionaryUtils.js
Labels: Proposal, UI Base Tools, Waiting for User Changes, bug

#438 Fixed error with value for list
  src/components/ADempiere/Field/FieldSelect.vue
Labels: UI Lookups, bug

#439 Fixed error with document action list component population
  src/components/ADempiere/Field/popover/documentStatus.vue
  src/components/ADempiere/WorkflowStatusBar/index.vue
Labels: UI Custom Lookups, bug

#440 Fixed error with ready for summit method for panel
  src/store/modules/ADempiere/panel.js
Labels: bug

#343 Set value to filter lookups list
  src/api/ADempiere/data.js
  src/components/ADempiere/Field/FieldSelect.vue
  src/store/modules/ADempiere/lookup.js
Labels: Base Changes, Proposal

#445 Feature/tets view
  package.json
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/DataTable/menu/menuTableMixin.js
  src/components/ADempiere/Field/FieldDate.vue
  src/components/ADempiere/Field/FieldNumber.vue
  src/components/ADempiere/Field/FieldYesNo.vue
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/Field/references.js
  src/router/modules/ADempiere/menu.js
  src/utils/ADempiere/dictionaryUtils.js
  src/utils/ADempiere/lookupFactory.js
  src/utils/ADempiere/references.js
  src/views/ADempiere/TestView/index.vue
Labels: Base Changes, UI Base Features, UI Base Tools

#444 Bugfix/validate filled fields before saving
  src/store/modules/ADempiere/panel.js
Labels: Base Changes, bug

#441 Activate the calculator enter action using a native JavaScript method
  src/components/ADempiere/Field/FieldNumber.vue
  src/components/ADempiere/Field/popover/calculator.vue
Labels: Base Changes, bug

#442 validate actions in Smart Browser
  src/components/ADempiere/ContextMenu/contextMenuDesktop.vue
Labels: Base Changes, bug

#447 Add support to POS service from API gRPC-POS-Client
  package.json
  src/api/ADempiere/pos.js
Labels: UI Base Tools

#448 feat: Add implementation grpc-Dictionary-Client v1.3.7
  package.json
  src/api/ADempiere/dictionary.js
Labels: Base Changes

#449 feat: Add support to grpc-dictionary-client v1.3.8
  package.json
  src/api/ADempiere/dictionary.js
Labels: Base Changes

#446 fix: Test View error when change value into field.
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/Field/FieldYesNo.vue
  src/components/ADempiere/Field/fieldSize.js
  src/components/ADempiere/Field/index.vue
  src/store/modules/ADempiere/browser.js
  src/store/modules/ADempiere/field.js
  src/store/modules/ADempiere/panel.js
  src/store/modules/ADempiere/window.js
  src/utils/ADempiere/dictionaryUtils.js
  src/utils/ADempiere/lookupFactory.js
  src/utils/ADempiere/references.js
  src/views/ADempiere/TestView/index.vue
Labels: UI Custom Lookups, UI Lookups

#450 feat: Add load dynamic form with fileName.
  package.json
  src/api/ADempiere/dictionary.js
  src/components/ADempiere/Form/PriceInquiry/index.vue
  src/components/ADempiere/Form/formMixin.js
  src/components/ADempiere/Form/index.vue
  src/store/modules/ADempiere/form.js
  src/styles/ADempiere/view.scss
  src/utils/ADempiere/dictionaryUtils.js
  src/utils/ADempiere/lookupFactory.js
  src/views/ADempiere/Form/index.vue
Labels: UI Base Features, UI Base Tools

#451 Add overwrite definition for factory
  src/utils/ADempiere/lookupFactory.js
  src/views/ADempiere/TestView/index.vue
Labels: Base Changes, UI Custom Lookups

#452 fix: Style form view.
  src/views/ADempiere/Form/index.vue
Labels: UI Tools

#453 Fixed error wuth login is too long when a session is expired
  src/store/modules/user.js
Labels: Security, bug

#454 Add Dictionary fields from ADempiere
  src/components/ADempiere/Form/PriceInquiry/index.vue
  src/components/ADempiere/Form/formMixin.js
  src/utils/ADempiere/lookupFactory.js
Labels: UI Base Features

#455 Add support to set warehouse and organization for current role
  package.json
  src/api/ADempiere/data.js
  src/layout/components/Sidebar/Logo.vue
  src/store/getters.js
  src/store/modules/user.js
  src/utils/ADempiere/auth.js
  src/views/permission/components/SwitchRoles.vue
  src/views/profile/components/Profile.vue
  src/views/profile/components/RolesNavbar.vue
  src/views/profile/components/UserCard.vue
  src/views/profile/components/role.vue
Labels: Base Changes

#457 Improves/reduce create form
  package.json
  src/api/ADempiere/pos.js
  src/components/ADempiere/Field/FieldBinary.vue
  src/components/ADempiere/Field/FieldColor.vue
  src/components/ADempiere/Field/FieldDate.vue
  src/components/ADempiere/Field/FieldImage.vue
  src/components/ADempiere/Field/FieldNumber.vue
  src/components/ADempiere/Field/FieldSelect.vue
  src/components/ADempiere/Field/FieldSelectMultiple.vue
  src/components/ADempiere/Field/FieldText.vue
  src/components/ADempiere/Field/FieldTextLong.vue
  src/components/ADempiere/Field/FieldTime.vue
  src/components/ADempiere/Field/FieldYesNo.vue
  src/components/ADempiere/Field/chatTextLong.vue
  src/components/ADempiere/Form/PriceInquiry/fieldsList.js
  src/components/ADempiere/Form/PriceInquiry/index.vue
  src/components/ADempiere/Form/formMixin.js
  src/store/modules/ADempiere/browser.js
  src/store/modules/ADempiere/panel.js
  src/store/modules/ADempiere/window.js
  src/utils/ADempiere/dictionaryUtils.js
  src/utils/ADempiere/lookupFactory.js
  src/views/ADempiere/Form/index.vue
  src/views/ADempiere/TestView/fieldsList.js
  src/views/ADempiere/TestView/index.vue
Labels: Base Changes, UI Base Features

#456 fix: Mandatory fields with value indicate that they are empty.
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/store/modules/ADempiere/panel.js
  src/utils/ADempiere/notification.js
Labels: bug

#458 Rename form
  src/components/ADempiere/Form/PriceChecking/fieldsList.js
  src/components/ADempiere/Form/PriceChecking/index.vue
Labels: UI Custom Lookups

#460 Add last version from gRPC data and POS
  package.json
Labels: Update Library

#461 Fixed error with set context from tables and browsers, it is a proble…
  src/store/modules/ADempiere/data.js
  src/store/modules/ADempiere/panel.js
  src/utils/ADempiere/contextUtils.js
Labels: Base Changes, bug

#462 fix infinite loop error in log record
  src/components/ADempiere/ContainerInfo/mixinInfo.js
Labels: bug

#463 Fixed Style Role Navbar
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/views/profile/components/RolesNavbar.vue
Labels: UI Base Features, enhancement

#465 lining up loading
  src/views/ADempiere/TestView/index.vue
Labels: bug

#466 Feature/#source code improve reorder implementation
  src/api/ADempiere/browser.js
  src/api/ADempiere/dashboard/dashboard.js
  src/api/ADempiere/data.js
  src/api/ADempiere/form/price-checking.js
  src/api/ADempiere/index.js
  src/api/ADempiere/persistence.js
  src/api/ADempiere/private-access.js
  src/api/ADempiere/process.js
  src/api/ADempiere/report.js
  src/api/ADempiere/rule.js
  src/api/ADempiere/system-core.js
  src/api/ADempiere/values.js
  src/api/ADempiere/window.js
  src/components/ADempiere/Dashboard/docstatus/index.vue
  src/components/ADempiere/Dashboard/index.vue
  src/components/ADempiere/Dashboard/recentItems/index.vue
  src/components/ADempiere/Dashboard/userfavorites/index.vue
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/Form/PriceChecking/index.vue
  src/store/modules/ADempiere/browserControl.js
  src/store/modules/ADempiere/calloutControl.js
  src/store/modules/ADempiere/containerInfo.js
  src/store/modules/ADempiere/contextMenu.js
  src/store/modules/ADempiere/dashboard.js
  src/store/modules/ADempiere/data.js
  src/store/modules/ADempiere/languageControl.js
  src/store/modules/ADempiere/lookup.js
  src/store/modules/ADempiere/processControl.js
  src/store/modules/ADempiere/reportControl.js
  src/store/modules/ADempiere/windowControl.js
  src/store/modules/user.js
Labels: Improve Source Code

#468 Remove unnecessary store
  src/store/modules/ADempiere/enrollment.js
  src/views/login/forgotPassword.vue
  src/views/login/setPassword.vue
  src/views/login/userEnrollment.vue
Labels: Improve Source Code

#469 Just rename some functions for a definition more clean
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
Labels: Improve Source Code

#464 feat: Change size component implementation
  src/components/ADempiere/Field/FieldDate.vue
  src/components/ADempiere/Field/FieldText.vue
  src/components/ADempiere/Field/fieldSize.js
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/Field/popover/calculator.vue
  src/components/ADempiere/Field/popover/operatorComparison.vue
  src/components/ADempiere/Panel/index.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/data.js
  src/store/modules/ADempiere/panel.js
  src/utils/ADempiere/dataUtils.js
  src/utils/ADempiere/dictionaryUtils.js
  src/utils/ADempiere/lookupFactory.js
  src/utils/ADempiere/references.js
  src/utils/ADempiere/valueUtils.js
Labels: Base Changes

#472 Add functionality for event handler from any field, it define the fol…
  src/components/ADempiere/Field/FieldDate.vue
  src/components/ADempiere/Field/FieldMixin.js
  src/components/ADempiere/Field/FieldNumber.vue
  src/components/ADempiere/Field/FieldText.vue
  src/components/ADempiere/Field/FieldTime.vue
  src/components/ADempiere/Field/FieldYesNo.vue
  src/store/modules/ADempiere/event.js
  src/store/modules/ADempiere/panel.js
Labels: Improve Source Code

#470 addAction
  src/components/ADempiere/Form/formMixin.js
  src/store/modules/ADempiere/contextMenu.js
Labels: Base Changes

#471 Hide and show context information
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/layout/components/Settings/index.vue
  src/store/modules/settings.js
  src/views/ADempiere/Browser/index.vue
  src/views/ADempiere/Form/index.vue
  src/views/ADempiere/Process/index.vue
  src/views/ADempiere/ReportViewer/index.vue
  src/views/ADempiere/Window/index.vue
Labels: UI Base Features, enhancement

#473 Bugfix/dynamic import
  package.json
  src/components/ADempiere/ContextMenu/index.vue
  src/components/ADempiere/Dashboard/index.vue
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/Form/index.vue
  src/components/ADempiere/Panel/index.vue
  src/store/modules/ADempiere/languageControl.js
  src/store/modules/ADempiere/panel.js
  src/store/modules/settings.js
  src/utils/ADempiere/valueUtils.js
  src/views/excel/merge-header.vue
  src/views/pdf/download.vue
Labels: bug

#474 Add support to conditional for event handler
  src/components/ADempiere/Field/FieldMixin.js
  src/utils/ADempiere/lookupFactory.js
Labels: Base Changes

#475 raname variable
  src/views/ADempiere/Browser/index.vue
  src/views/ADempiere/Form/index.vue
  src/views/ADempiere/Process/index.vue
  src/views/ADempiere/ReportViewer/index.vue
  src/views/ADempiere/Window/index.vue
Labels: bug

#476 add get country to system core
  src/api/ADempiere/system-core.js
Labels: bug
