Repository adempiere/adempiere-vue, pull requests merged in 2020-01, with the labels that each got.

#183 add drill down support to reports
  src/api/ADempiere/data.js
  src/components/ADempiere/ContextMenu/contextMenuDesktop.vue
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/ContextMenu/index.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/layout/components/TagsView/index.vue
  src/router/modules/ADempiere/menu.js
  src/store/modules/ADempiere/data.js
  src/store/modules/ADempiere/panel.js
  src/store/modules/ADempiere/processControl.js
  src/store/modules/ADempiere/reportControl.js
  src/store/modules/tagsView.js
  src/utils/ADempiere/dictionaryUtils.js
  src/views/ADempiere/ReportViewer/index.vue
Labels: Base Changes, UI Base Features, Waiting for User Changes

#215 Add Tag to Document Status
  src/components/ADempiere/DataTable/index.vue
  src/views/ADempiere/Window/index.vue
Labels: UI Base Features

#212 Support to process the selection of records
  src/components/ADempiere/DataTable/contextMenu.vue
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/DataTable/menu/contextMenu.vue
  src/components/ADempiere/DataTable/menu/index.vue
  src/components/ADempiere/DataTable/menu/mixinMenu.js
  src/components/ADempiere/Dialog/index.vue
  src/components/ADempiere/Field/FieldDate.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/processControl.js
  src/store/modules/ADempiere/utils.js
  src/views/ADempiere/ProcessActivity/index.vue
Labels: UI Base Features, UI Base Tools

#213 add support to language list gRPC service
  src/api/ADempiere/data.js
  src/store/modules/ADempiere/data.js
  src/store/modules/ADempiere/utils.js
  src/views/profile/components/RolesNavbar.vue
  src/views/profile/components/role.vue
Labels: Base Changes, Waiting for User Changes

#216 fix: Fix the display column of the lookup when it has a default value.
  src/components/ADempiere/Field/FieldSelect.vue
  src/store/modules/ADempiere/context.js
  src/store/modules/ADempiere/lookup.js
Labels: Base Changes, UI Custom Lookups

#220 fix: Context menu style for record tables.
  src/components/ADempiere/DataTable/index.vue
Labels: Base Changes

#219 Support to dynamic dashboard
  src/api/ADempiere/data.js
  src/components/ADempiere/Dashboard/docstatus/index.vue
  src/components/ADempiere/Dashboard/favourites/index.vue
  src/components/ADempiere/Dashboard/index.vue
  src/components/ADempiere/Dashboard/recentItems/index.vue
  src/store/modules/ADempiere/dashboard.js
  src/views/dashboard/admin/index.vue
Labels: UI Base Tools, Waiting for User Changes

#218 Add support to generate report from print format
  src/api/ADempiere/data.js
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/router/modules/ADempiere/menu.js
  src/store/modules/ADempiere/process.js
  src/store/modules/ADempiere/processControl.js
  src/utils/ADempiere/dictionaryUtils.js
  src/views/ADempiere/ReportViewer/index.vue
Labels: Base Changes, Waiting for User Changes

#217 fix: The values are lost from the list of changed fields.
  src/components/ADempiere/Field/FieldDate.vue
  src/components/ADempiere/Panel/index.vue
  src/store/modules/ADempiere/data.js
  src/store/modules/ADempiere/panel.js
Labels: UI Lookups, Waiting for User Changes

#214 redefine API to provide business data
  package.json
  src/api/ADempiere/data.js
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/Dashboard/docstatus/index.vue
  src/components/ADempiere/Dashboard/favourites/index.vue
  src/components/ADempiere/Dashboard/index.vue
  src/components/ADempiere/Dashboard/recentItems/index.vue
  src/components/ADempiere/Panel/index.vue
  src/components/ADempiere/RecentItems/index.vue
  src/lang/ADempiere/en.js
  src/store/modules/ADempiere/browserControl.js
  src/store/modules/ADempiere/calloutControl.js
  src/store/modules/ADempiere/dashboard.js
  src/store/modules/ADempiere/data.js
  src/store/modules/ADempiere/lookup.js
  src/store/modules/ADempiere/process.js
  src/store/modules/ADempiere/processControl.js
  src/store/modules/ADempiere/reportControl.js
  src/store/modules/ADempiere/utils.js
  src/store/modules/ADempiere/windowControl.js
  src/views/ADempiere/ProcessActivity/index.vue
  src/views/dashboard/admin/index.vue
  src/views/profile/components/recentItems.vue
Labels: Base Changes, Waiting for User Changes

#221 bugfix duplicated recent items folder and file
  src/components/ADempiere/RecentItems/index.vue
Labels: Base Changes

#223 fix: Mandatory logic on first field load.
  src/components/ADempiere/Field/FieldText.vue
  src/components/ADempiere/Panel/filterFields.vue
  src/store/modules/ADempiere/panel.js
Labels: Base Changes

#222 remove recent items implementation from profile page
  src/views/profile/components/RolesNavbar.vue
  src/views/profile/components/recentItems.vue
  src/views/profile/components/role.vue
  src/views/profile/index.vue
Labels: Base Changes

#224 Support Record Scroll
  package.json
  src/App.vue
  src/components/ADempiere/ContextMenu/contextMenuDesktop.vue
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/DataTable/index.vue
  src/main.js
  src/views/ADempiere/Window/index.vue
Labels: Base Changes, UI Base Tools

#225 fix: Error when logout from a Window.
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
Labels: Base Changes

#226 Add validation to personal lock by role
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/store/modules/ADempiere/data.js
  src/store/modules/user.js
Labels: Base Changes

#227 Add Calendar to Dashboard
  package.json
  src/components/ADempiere/Dashboard/calendar/index.vue
  src/components/ADempiere/Dashboard/index.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
Labels: UI Base Features

#228 Add Export in Zip
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/DataTable/menu/index.vue
  src/components/ADempiere/DataTable/menu/mixinMenu.js
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/utils/ADempiere/exportUtil.js
Labels: Base Changes

#229 Add support to translations (Tab Translations).
  package.json
  src/api/ADempiere/data.js
  src/components/ADempiere/Field/fieldTranslated.vue
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/Panel/index.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/layout/components/Navbar.vue
  src/store/modules/ADempiere/languageControl.js
  src/store/modules/ADempiere/utils.js
  src/views/profile/components/Profile.vue
  src/views/profile/components/RolesNavbar.vue
  src/views/profile/components/role.vue
Labels: Base Changes

#230 fix: Context menu icons are lost when the main menu is hidden.
  src/components/ADempiere/ContextMenu/index.vue
  src/components/ADempiere/ContextMenu/items.vue
Labels: Base Changes

#232 Compatibility Error es-lint
  package.json
Labels: bug

#234 Solve empty menu in relationships
  src/App.vue
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/DataTable/menu/mixinMenu.js
Labels: Base Changes

#235 Fixed Style of Dashboard
  src/views/dashboard/admin/index.vue
Labels: UI Base Tools

#236 feat: Add support to gRPC Business Data Client version 1.9.0
  package.json
  src/api/ADempiere/data.js
  src/api/ADempiere/index.js
  src/components/ADempiere/Dashboard/favourites/index.vue
  src/components/ADempiere/Dashboard/recentItems/index.vue
  src/components/ADempiere/Dialog/index.vue
  src/store/modules/ADempiere/dashboard.js
  src/store/modules/ADempiere/languageControl.js
  src/store/modules/ADempiere/processControl.js
  src/store/modules/ADempiere/reportControl.js
Labels: Base Changes

#238 bugfix load data when references zoom in
  src/components/ADempiere/Panel/index.vue
Labels: UI Base Tools

#240 bugfix max page size for pagination
  src/components/ADempiere/DataTable/index.vue
Labels: UI Base Tools

#242 Change version for data client to 1.9.1
  package.json
Labels: Base Changes

#250 correcting error export zip text file
  src/components/ADempiere/DataTable/menu/mixinMenu.js
Labels: Base Changes

#251 feat: Add data client API implementation for Chat Entry and Record Chat.
  package.json
  src/api/ADempiere/data.js
Labels: Base Changes

#248 validate personal lock by role
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
Labels: UI Base Features

#253 Bugfix zoom process from process activity
  src/api/ADempiere/data.js
  src/store/modules/ADempiere/processControl.js
  src/views/ADempiere/ProcessActivity/index.vue
Labels: Base Changes

#255 bugfix print format selection after report
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/store/modules/ADempiere/processControl.js
  src/utils/ADempiere/dictionaryUtils.js
Labels: Base Changes

#256 fix: Show/hidden optional columns in table.
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/DataTable/menu/index.vue
  src/components/ADempiere/DataTable/menu/mixinMenu.js
  src/store/modules/ADempiere/panel.js
Labels: Base Changes

#254 fix: Show/hidden totals in table.
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/DataTable/menu/contextMenu.vue
  src/components/ADempiere/DataTable/menu/index.vue
  src/components/ADempiere/DataTable/menu/mixinMenu.js
  src/components/ADempiere/Field/FieldNumber.vue
  src/components/ADempiere/Field/references.js
  src/utils/ADempiere/dictionaryUtils.js
Labels: Base Changes

#258 fix: Read only to field type Text Long.
  package.json
  src/components/ADempiere/Field/FieldTextLong.vue
Labels: Base Changes

#260 bugfix load record from recent item
  src/components/ADempiere/Panel/index.vue
Labels: UI Base Features

#262 bugfix set void values from callout
  src/components/ADempiere/Field/FieldSelect.vue
  src/store/modules/ADempiere/calloutControl.js
Labels: Base Changes

#263 fix: Send context to process associated.
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/Tab/tabMixin.js
  src/store/modules/ADempiere/browser.js
  src/store/modules/ADempiere/browserControl.js
  src/store/modules/ADempiere/context.js
  src/store/modules/ADempiere/data.js
  src/store/modules/ADempiere/lookup.js
  src/store/modules/ADempiere/panel.js
  src/store/modules/ADempiere/process.js
  src/store/modules/ADempiere/window.js
  src/store/modules/ADempiere/windowControl.js
  src/utils/ADempiere/contextUtils.js
  src/utils/ADempiere/dictionaryUtils.js
Labels: Base Changes

#264 Add action for zoom record from SB in new table menu implementation
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/DataTable/menu/index.vue
  src/components/ADempiere/DataTable/menu/mixinMenu.js
Labels: Base Changes

#265 add support to dashboard collapsible and open by default
  src/components/ADempiere/Dashboard/calendar/index.vue
  src/components/ADempiere/Dashboard/docstatus/index.vue
  src/components/ADempiere/Dashboard/favourites/index.vue
  src/components/ADempiere/Dashboard/index.vue
  src/components/ADempiere/Dashboard/recentItems/index.vue
  src/components/ADempiere/Dropdown/index.vue
Labels: UI Base Features

#266 Support record Log of container info
  src/components/ADempiere/Field/FieldTextLong.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/containerInfo.js
  src/store/modules/ADempiere/utils.js
  src/store/modules/ADempiere/windowControl.js
  src/views/ADempiere/Window/index.vue
Labels: UI Base Features

#267 fix: Uncaught exception in promises, and remove log consoles.
  package.json
  src/api/ADempiere/data.js
  src/components/ADempiere/Dashboard/docstatus/index.vue
  src/components/ADempiere/Dashboard/favourites/index.vue
  src/components/ADempiere/Dashboard/index.vue
  src/components/ADempiere/Dashboard/recentItems/index.vue
  src/components/ADempiere/Field/FieldSelect.vue
  src/lang/ADempiere/en.js
  src/store/modules/ADempiere/browser.js
  src/store/modules/ADempiere/containerInfo.js
  src/store/modules/ADempiere/dashboard.js
  src/store/modules/ADempiere/languageControl.js
  src/store/modules/ADempiere/process.js
  src/utils/ADempiere/contextUtils.js
  src/views/ADempiere/Browser/index.vue
  src/views/ADempiere/Process/index.vue
  src/views/profile/components/RolesNavbar.vue
  src/views/profile/components/role.vue
Labels: Base Changes

#269 fix error with share link action
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/Panel/index.vue
Labels: Base Changes

#270 bugfix validation of get private access
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/store/modules/ADempiere/data.js
Labels: Base Changes

#280 support dashboards associated to the selected role
  src/views/dashboard/admin/index.vue
  src/views/profile/components/RolesNavbar.vue
Labels: Base Changes, UI Base Tools

#272 Add ListRecordChat and ListChatEntries
  src/api/ADempiere/data.js
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/containerInfo.js
  src/views/ADempiere/Window/index.vue
Labels: Base Changes, UI Tools

#273 bugfix documents pending filter
  src/components/ADempiere/Panel/index.vue
  src/store/modules/ADempiere/panel.js
Labels: Base Changes, UI Base Tools

#275 bugfix send email to enrollment user
  src/api/ADempiere/enrollment.js
  src/store/modules/ADempiere/enrollment.js
Labels: Base Changes

#278 fix: #277 Context menu relations.
  src/components/ADempiere/ContextMenu/contextMenuDesktop.vue
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/ContextMenu/contextMenuMobile.vue
  src/components/ADempiere/Dashboard/docstatus/index.vue
  src/components/ADempiere/Dashboard/recentItems/index.vue
  src/components/ADempiere/DataTable/menu/mixinMenu.js
  src/components/ADempiere/Field/index.vue
  src/router/modules/ADempiere/menu.js
  src/store/modules/ADempiere/contextMenu.js
  src/store/modules/ADempiere/windowControl.js
  src/store/modules/permission.js
  src/utils/ADempiere/valueUtils.js
  src/views/ADempiere/ProcessActivity/index.vue
  src/views/ADempiere/Window/index.vue
Labels: UI Base Tools

#281 refactor: Separate context info field in component.
  src/components/ADempiere/Field/fieldContextInfo.vue
  src/components/ADempiere/Field/index.vue
Labels: Base Changes

#276 bugfix open process activity from process notifications
  src/components/ADempiere/Badge/index.vue
  src/views/ADempiere/ProcessActivity/index.vue
Labels: UI Base Tools

#282 resolve disabled error with element-ui tabs component
  src/views/ADempiere/Window/index.vue
Labels: UI Base Features

#284 add popover of Workflow log
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/containerInfo.js
  src/utils/ADempiere/valueUtils.js
  src/views/ADempiere/Window/index.vue
Labels: UI Base Tools

#285 fix: Undefined method.
  src/components/ADempiere/ContextMenu/contextMenuDesktop.vue
  src/components/ADempiere/ContextMenu/contextMenuMobile.vue
  src/components/ADempiere/ContextMenu/items.vue
  src/components/ADempiere/Field/FieldMixin.js
  src/components/ADempiere/Field/FieldSelect.vue
  src/components/ADempiere/Field/index.vue
  src/store/modules/ADempiere/panel.js
  src/store/modules/ADempiere/processControl.js
  src/store/modules/user.js
Labels: Base Changes, bug

#286 fix: Zoom window in context info field.
  src/components/ADempiere/Field/fieldContextInfo.vue
  src/components/ADempiere/Field/index.vue
Labels: Base Changes, bug

#288 group by logId
  src/views/ADempiere/Window/index.vue
Labels: UI Base Tools

#290 bugfix add fields to advanced query
  src/store/modules/ADempiere/panel.js
Labels: Base Changes

#287 feat: Add operators comparison to advanced search.
  src/api/ADempiere/data.js
  src/components/ADempiere/Field/FieldDate.vue
  src/components/ADempiere/Field/FieldSelect.vue
  src/components/ADempiere/Field/FieldSelectMultiple.vue
  src/components/ADempiere/Field/fieldOperatorComparison.vue
  src/components/ADempiere/Field/fieldTranslated.vue
  src/components/ADempiere/Field/index.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/data.js
  src/store/modules/ADempiere/panel.js
  src/store/modules/ADempiere/windowControl.js
  src/utils/ADempiere/dataUtils.js
  src/utils/ADempiere/dictionaryUtils.js
  src/utils/ADempiere/valueUtils.js
Labels: Base Changes

#291 Support add comment
  src/api/ADempiere/data.js
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/containerInfo.js
  src/views/ADempiere/Window/index.vue
Labels: Base Changes

#293 fix: RegExp operand's in logic to evaluator.
  src/utils/ADempiere/evaluator.js
Labels: Base Changes

#294 Change version for 2.0.5 of data
  package.json
Labels: Base Changes, Update Library
