Repository adempiere/adempiere-vue, pull requests merged in 2020-03, with the labels that each got.

#381 identificate new record
  src/components/ADempiere/DataTable/index.vue
Labels: UI Custom Lookups, bug

#382 Add default icon to run a Report or Process by default
  src/components/ADempiere/ContextMenu/contextMenuMobile.vue
  src/components/ADempiere/ContextMenu/index.vue
Labels: Base Changes, UI Lookups

#383 unnecessary requests
  src/components/ADempiere/Panel/index.vue
  src/components/ADempiere/WorkflowStatusBar/index.vue
  src/views/ADempiere/Window/index.vue
Labels: Base Changes, bug

#385 fix: #384 Unnecessary request in tab children.
  src/components/ADempiere/Tab/tabChildren.vue
Labels: Base Changes

#387 fix: #386 Value preference with session context.
  src/store/modules/ADempiere/browser.js
  src/store/modules/ADempiere/panel.js
  src/store/modules/ADempiere/window.js
  src/utils/ADempiere/contextUtils.js
  src/utils/ADempiere/dictionaryUtils.js
Labels: Base Changes

#388 Show sequence options in the table menu
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/DataTable/menu/index.vue
  src/components/ADempiere/DataTable/menu/menuTableMixin.js
  src/store/modules/ADempiere/window.js
Labels: Base Changes, bug

#389 fix set field definitions
  src/components/ADempiere/DataTable/index.vue
Labels: Base Changes

#390 bugfix load context info of fields
  src/store/modules/ADempiere/panel.js
Labels: Base Changes, UI Base Features

#391 fix: Default values that are @SQL= on the first load
  src/api/ADempiere/data.js
  src/components/ADempiere/Field/FieldMixin.js
  src/store/modules/ADempiere/browser.js
  src/store/modules/ADempiere/browserControl.js
  src/store/modules/ADempiere/data.js
  src/store/modules/ADempiere/panel.js
  src/utils/ADempiere/contextUtils.js
  src/utils/ADempiere/dictionaryUtils.js
  src/utils/ADempiere/valueUtils.js
  src/views/ADempiere/Browser/index.vue
Labels: Base Changes

#392 solve problems of split panel styles
  src/views/ADempiere/Window/index.vue
Labels: UI Base Features

#396 fix: #395 The references associated with a record are not displayed.
  src/components/ADempiere/ContextMenu/contextMenuDesktop.vue
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/ContextMenu/contextMenuMobile.vue
  src/components/ADempiere/Panel/index.vue
  src/store/modules/ADempiere/windowControl.js
Labels: Base Changes, bug

#397 improves: Add state restart for modules that manage and store data.
  plop-templates/ADempiere/store/index.hbs
  src/store/modules/ADempiere/containerInfo.js
  src/store/modules/ADempiere/contextMenu.js
  src/store/modules/ADempiere/data.js
  src/store/modules/ADempiere/languageControl.js
  src/store/modules/ADempiere/lookup.js
  src/store/modules/ADempiere/processControl.js
  src/store/modules/ADempiere/reportControl.js
  src/store/modules/ADempiere/utils.js
  src/store/modules/ADempiere/window.js
  src/store/modules/ADempiere/windowControl.js
  src/store/modules/user.js
Labels: Base Changes

#399 fix: #398 Wrong distribution of field size.
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/Field/FieldText.vue
  src/components/ADempiere/Field/FieldYesNo.vue
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/Field/references.js
  src/components/ADempiere/Panel/index.vue
Labels: UI Base Tools

#403 Select at 0 in the table
  src/components/ADempiere/DataTable/index.vue
Labels: bug

#405 fix: Loses role of session.
  src/api/user.js
  src/store/modules/user.js
  src/views/login/index.vue
Labels: bug

#402 fix: #401 Display logics show more fields than they need to be
  src/components/ADempiere/Field/index.vue
  src/store/modules/ADempiere/panel.js
  src/utils/ADempiere/contextUtils.js
  src/utils/ADempiere/dictionaryUtils.js
  src/utils/ADempiere/evaluator.js
Labels: UI Lookups

#406 indicate new record in parent table
  src/components/ADempiere/DataTable/index.vue
Labels: Base Changes, UI Base Tools

#407 fix: Display values in fields lookup
  src/components/ADempiere/Field/FieldSelect.vue
  src/components/ADempiere/Field/popover/documentStatus.vue
  src/components/ADempiere/Panel/index.vue
  src/store/modules/ADempiere/panel.js
  src/utils/ADempiere/dictionaryUtils.js
  src/utils/ADempiere/valueUtils.js
Labels: Base Changes, UI Lookups

#409 fix #410 load data in tab childs after save record
  src/components/ADempiere/Tab/tabChildren.vue
Labels: Base Changes, bug

#412 fix: Console error when login redirect to window.
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/DataTable/menu/index.vue
  src/views/login/forgotPassword.vue
  src/views/login/index.vue
  src/views/login/loginMixin.js
  src/views/login/setPassword.vue
  src/views/login/userEnrollment.vue
Labels: bug

#413 fix: Run process notification without session
  src/api/ADempiere/data.js
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/store/modules/ADempiere/processControl.js
  src/utils/ADempiere/notification.js
Labels: bug

#414 fix: Print formats unnecessary request.
  src/components/ADempiere/ContextMenu/contextMenuMobile.vue
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/browser.js
  src/store/modules/ADempiere/contextMenu.js
  src/store/modules/ADempiere/process.js
  src/store/modules/ADempiere/reportControl.js
  src/store/modules/ADempiere/window.js
Labels: Improve Source Code

#418 fix: Run callout's after change values in all field's.
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/calloutControl.js
  src/store/modules/ADempiere/panel.js
Labels: Base Changes, bug

#415 fix: Reset parameters after run Process.
  src/store/modules/ADempiere/panel.js
  src/store/modules/ADempiere/processControl.js
  src/utils/ADempiere/dictionaryUtils.js
Labels: bug

#380 bugfix send values to server from calculator
  src/components/ADempiere/Field/FieldNumber.vue
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/Field/popover/calculator.vue
  src/utils/ADempiere/valueUtils.js
Labels: bug

#420 fix: Run print format without operator's.
  src/store/modules/ADempiere/panel.js
  src/store/modules/ADempiere/reportControl.js
  src/utils/ADempiere/dictionaryUtils.js
Labels: bug

#422 fix #421 Display field type date in table
  src/components/ADempiere/Field/FieldDate.vue
Labels: Base Changes, bug
