Repository adempiere/adempiere-vue, pull requests merged in 2020-11, with the labels that each got.

#536 moving config.json to config folder
  config/config.json
  src/api/ADempiere/instances.js
  src/utils/ADempiere/resource.js
Labels: Base Changes

#537 The History of changes does not show the detail
  src/components/ADempiere/ContainerInfo/recordLogs.vue
  src/store/modules/ADempiere/persistence.js
  src/utils/ADempiere/apiConverts/window.js
Labels: UI Base Tools, UI Tools

#538 change client ID to role Uuid and organization ID to organization Uuid
  src/router/modules/ADempiere/menu.js
Labels: Base Changes

#539 add document status bar
  src/api/ADempiere/window.js
  src/components/ADempiere/ContainerInfo/workflowLogs.vue
  src/store/modules/ADempiere/containerInfo.js
  src/views/ADempiere/Window/index.vue
Labels: bug

#540 Bugfix/procces error
  src/store/modules/ADempiere/report.js
  src/utils/ADempiere/apiConverts/process.js
Labels: Base Changes, bug

#541 Solving Problem of the advanced search of Window, Report, Processes, …
  src/components/HeaderSearch/index.vue
Labels: bug

#545 fix: Relations in context menu.
  src/components/ADempiere/ContextMenu/contextMenuDesktop.vue
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/ContextMenu/contextMenuMobile.vue
  src/components/ADempiere/ContextMenu/itemsRelations.vue
  src/components/ADempiere/ContextMenu/relationsMixin.js
  src/components/ADempiere/DropdownMenu/index.vue
  src/router/modules/ADempiere/menu.js
  src/store/modules/ADempiere/contextMenu.js
  src/store/modules/permission.js
  src/store/modules/user.js
  src/utils/ADempiere/valueUtils.js
  src/views/ADempiere/Summary/index.vue
Labels: Base Changes, UI Base Features

#546 * correcting price query errors with the barcode
  src/api/ADempiere/persistence.js
  src/components/ADempiere/Form/PriceChecking/fieldsList.js
  src/components/ADempiere/Form/PriceChecking/index.vue
  src/components/ADempiere/Form/VPOS/KeyLayout/index.vue
  src/components/Screenfull/index.vue
  src/layout/components/Settings/index.vue
  src/layout/index.vue
  src/settings.js
  src/store/modules/settings.js
Labels: Base Changes, UI Base Features

#544 feat: Change api config from function to constant.
  config/default.json
  src/api/ADempiere/instances.js
  src/utils/ADempiere/config.js
  src/utils/ADempiere/resource.js
Labels: Base Changes, Update Library

#547 fix: Calculator popover style.
  src/components/ADempiere/Field/popover/calculator/buttons.js
  src/components/ADempiere/Field/popover/calculator/index.vue
Labels: Base Changes

#549 add the price query window to the rais menu
  src/components/ADempiere/Form/index.vue
  src/layout/components/Settings/index.vue
  src/layout/index.vue
  src/router/modules/ADempiere/staticRoutes.js
Labels: UI Base Tools
