Repository adempiere/adempiere-vue, pull requests merged in 2020-12, with the labels that each got.

#550 barcode Reader
  src/api/user.js
  src/components/ADempiere/Form/BarcodeReader/fieldsList.js
  src/components/ADempiere/Form/BarcodeReader/fieldsListBarCode.js
  src/components/ADempiere/Form/BarcodeReader/index.vue
  src/components/ADempiere/Form/PriceChecking/index.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/router/modules/ADempiere/staticRoutes.js
  src/store/modules/user.js
  src/utils/ADempiere/apiConverts/core.js
  src/views/ADempiere/Form/index.vue
Labels: UI Custom Lookups

#553 fix: Relations in context menu.
  src/components/ADempiere/ContextMenu/index.vue
  src/components/ADempiere/ContextMenu/relationsMixin.js
  src/router/modules/ADempiere/menu.js
  src/utils/ADempiere/valueUtils.js
Labels: Base Changes

#555 Add big total converted
  src/components/ADempiere/Form/ProductInfo/productList.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
Labels: Base Changes, UI Custom Lookups

#556 add traslation the title
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/views/ADempiere/Form/index.vue
Labels: UI Base Features

#558 fix: Lookup item direct query columnName not exist
  src/api/ADempiere/values.js
  src/components/ADempiere/Field/FieldSelect.vue
  src/store/modules/ADempiere/lookup.js
  src/store/modules/ADempiere/panel/actions.js
Labels: Base Changes

#559 Add default image when organizationImagePath is Empty
  src/components/ADempiere/Form/PriceChecking/index.vue
Labels: Base Changes

#561 Correct order search error
  src/api/ADempiere/form/point-of-sales.js
  src/components/ADempiere/Form/VPOS/Options/index.vue
  src/components/ADempiere/Form/VPOS/OrderList/index.vue
  src/components/ADempiere/Form/VPOS/ProductInfo/index.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
Labels: UI Tools

#560 print label from table
  src/components/ADempiere/Form/ProductInfo/index.vue
  src/components/ADempiere/Form/ProductInfo/productList.vue
  src/components/ADempiere/Form/VPOS/Collection/index.vue
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/store/modules/ADempiere/pointOfSales/collection.js
  src/store/modules/ADempiere/pointOfSales/index.js
  src/store/modules/ADempiere/process.js
  src/utils/ADempiere/constants/zoomReport.js
  src/views/ADempiere/Form/index.vue
Labels: UI Base Tools

#562 add validation at the time of creating the business partner
  src/components/ADempiere/Form/PriceChecking/index.vue
  src/components/ADempiere/Form/VPOS/BusinessPartner/businessPartnerCreate.vue
  src/components/ADempiere/Form/VPOS/BusinessPartner/fieldsListCreate.js
  src/components/ADempiere/Form/VPOS/BusinessPartner/index.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/layout/components/Sidebar/index.vue
  src/router/modules/ADempiere/staticRoutes.js
  src/views/ADempiere/ProcessActivity/index.vue
Labels: Base Changes
