Repository adempiere/adempiere-vue, pull requests merged in 2020-02, with the labels that each got.

#297 bugfix load values of field Target Document Type
  src/components/ADempiere/Tab/tabMixin.js
  src/store/modules/ADempiere/browserControl.js
  src/store/modules/ADempiere/lookup.js
  src/store/modules/ADempiere/windowControl.js
  src/utils/ADempiere/contextUtils.js
Labels: Base Changes, bug

#299 fix: The fields of type Yes-No and Number, take the fields as empty .
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/Field/FieldMixin.js
  src/store/modules/ADempiere/panel.js
  src/store/modules/ADempiere/window.js
  src/utils/ADempiere/contextUtils.js
  src/utils/ADempiere/dictionaryUtils.js
  src/utils/ADempiere/valueUtils.js
Labels: Base Changes, bug

#300 bugfix close affix tags views
  src/layout/components/TagsView/index.vue
Labels: Base Changes, UI Tools

#301 fix: Evaluate multiple logic's with | and &.
  src/utils/ADempiere/evaluator.js
Labels: Base Changes, bug

#298 changing chat structure and asynchronous methods
  src/api/ADempiere/data.js
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/containerInfo.js
  src/views/ADempiere/Window/index.vue
Labels: Base Changes

#303 fix: #302 Long text or Memo field takes the value of the previously selected record.
  src/api/ADempiere/data.js
  src/components/ADempiere/Field/FieldText.vue
  src/components/ADempiere/Field/FieldTextLong.vue
  src/components/ADempiere/Field/references.js
  src/store/modules/ADempiere/panel.js
Labels: Base Changes, UI Lookups

#304 docs: Add Pull Request template.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#305 Add tag to document states to activities
  src/components/ADempiere/DataTable/index.vue
  src/store/modules/ADempiere/containerInfo.js
  src/utils/ADempiere/globalMethods.js
  src/utils/ADempiere/valueUtils.js
  src/views/ADempiere/Window/index.vue
Labels: Base Changes, UI Lookups

#307 fix: Update the search if a field with value is hidden or showed.
  src/store/modules/ADempiere/panel.js
  src/utils/ADempiere/dictionaryUtils.js
Labels: Base Changes

#309 feat: Add API support to gRPC-Data-Client v2-0.6.
  package.json
  src/api/ADempiere/data.js
Labels: Update Library

#312 refactor of shortcout
  src/components/ADempiere/DataTable/index.vue
Labels: Base Changes

#313 fix: Multiple requests block the browser.
  src/api/ADempiere/data.js
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/Field/FieldMixin.js
  src/components/ADempiere/Field/FieldSelect.vue
  src/components/ADempiere/Field/FieldYesNo.vue
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/Panel/index.vue
  src/store/modules/ADempiere/data.js
  src/store/modules/ADempiere/panel.js
  src/store/modules/ADempiere/window.js
  src/utils/ADempiere/dictionaryUtils.js
  src/views/ADempiere/Window/index.vue
Labels: UI Base Tools

#315 fix #314 Wrong display of the Window references in the context menu.
  src/components/ADempiere/ContextMenu/contextMenuDesktop.vue
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/ContextMenu/contextMenuMobile.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
Labels: Base Changes, bug

#318 Refactor code, remove unused methods and optimized application.
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/DataTable/menu/contextMenu.vue
  src/components/ADempiere/DataTable/menu/index.vue
  src/components/ADempiere/DataTable/menu/mixinMenu.js
  src/components/ADempiere/Dropdown/index.vue
  src/components/ADempiere/Field/FieldSelect.vue
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/Panel/detail.vue
  src/components/ADempiere/Panel/index.vue
  src/components/ADempiere/Tab/index.vue
  src/components/ADempiere/Tab/tabChildren.vue
  src/components/ADempiere/Tab/tabMixin.js
  src/layout/components/AppMain.vue
  src/layout/components/TagsView/index.vue
  src/store/modules/ADempiere/browser.js
  src/store/modules/ADempiere/data.js
  src/store/modules/ADempiere/languageControl.js
  src/store/modules/ADempiere/lookup.js
  src/store/modules/ADempiere/panel.js
  src/store/modules/ADempiere/process.js
  src/store/modules/ADempiere/utils.js
  src/store/modules/ADempiere/window.js
  src/store/modules/ADempiere/windowControl.js
  src/store/modules/user.js
  src/utils/ADempiere/dictionaryUtils.js
  src/views/ADempiere/Browser/index.vue
  src/views/ADempiere/ReportViewer/index.vue
  src/views/ADempiere/Window/index.vue
  src/views/profile/components/RolesNavbar.vue
  src/views/profile/components/role.vue
Labels: Base Changes

#311 Bugfix create order lines
  src/store/modules/ADempiere/data.js
  src/store/modules/ADempiere/panel.js
  src/utils/ADempiere/contextUtils.js
Labels: Base Changes

#317 fix: #316 Add Smart Browser validation to research with mandatory parameters.
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/store/modules/ADempiere/browser.js
  src/store/modules/ADempiere/panel.js
  src/utils/ADempiere/dictionaryUtils.js
  src/utils/ADempiere/valueUtils.js
Labels: Base Changes, Waiting for User Changes, bug

#325 fix: Export record in table, and mobile support to Smart Browser.
  src/components/ADempiere/ContextMenu/contextMenuDesktop.vue
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/ContextMenu/contextMenuMobile.vue
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/DataTable/menu/index.vue
  src/components/ADempiere/DataTable/menu/menuTableMixin.js
  src/components/ADempiere/DataTable/menu/tableContextMenu.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/store/modules/user.js
Labels: Base Changes, bug

#324 bugfix multiple call for lookup item
  src/components/ADempiere/Field/FieldSelect.vue
  src/store/modules/ADempiere/calloutControl.js
  src/store/modules/ADempiere/panel.js
Labels: Base Changes, bug

#326 bugfix display tag view in mobile device
  src/layout/components/TagsView/ScrollPane.vue
Labels: Base Changes, bug

#329 fix: #328 Delete record with contextual menu in data table.
  src/components/ADempiere/ContextMenu/contextMenuDesktop.vue
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/ContextMenu/contextMenuMobile.vue
  src/components/ADempiere/DataTable/menu/index.vue
  src/components/ADempiere/DataTable/menu/menuTableMixin.js
  src/components/ADempiere/DataTable/menu/tableContextMenu.vue
  src/store/modules/ADempiere/windowControl.js
Labels: Base Changes, bug

#331 fix #330 Position style to contextual menu in data table.
  src/components/ADempiere/DataTable/index.vue
Labels: Base Changes

#322 correcting container info chats errors
  package.json
  src/components/ADempiere/ContainerInfo/chatEntries.vue
  src/components/ADempiere/ContainerInfo/mixinInfo.js
  src/components/ADempiere/ContainerInfo/recordLogs.vue
  src/components/ADempiere/ContainerInfo/workflowLogs.vue
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/Field/chatTextLong.vue
  src/components/ADempiere/Field/index.vue
  src/main.js
  src/store/modules/ADempiere/containerInfo.js
  src/store/modules/ADempiere/contextMenu.js
  src/store/modules/ADempiere/processControl.js
  src/store/modules/ADempiere/utils.js
  src/views/ADempiere/Window/index.vue
Labels: Base Changes

#333 bugfix login from redirect
  src/layout/components/Navbar.vue
  src/store/modules/user.js
  src/views/login/index.vue
Labels: bug

#335 fix: #334 Display logic that prevents some fields from being displayed.
  src/components/ADempiere/Panel/index.vue
  src/main.js
  src/store/modules/ADempiere/panel.js
  src/utils/ADempiere/evaluator.js
Labels: bug

#337 fix: #336 Not search records with NULL or NOT NULL operators.
  src/components/ADempiere/Field/fieldPopovers/fieldContextInfo.vue
  src/components/ADempiere/Field/fieldPopovers/fieldOperatorComparison.vue
  src/components/ADempiere/Field/fieldPopovers/fieldTranslated.vue
  src/components/ADempiere/Field/index.vue
Labels: bug

#338 indicate new row
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/Field/FieldMixin.js
  src/components/ADempiere/Field/FieldText.vue
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/Panel/index.vue
Labels: Base Changes

#339 fix: Not resend request when hidden document status.
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/Field/fieldPopovers/fieldContextInfo.vue
  src/components/ADempiere/Field/fieldPopovers/fieldDocumentStatus.vue
  src/components/ADempiere/Field/index.vue
  src/store/modules/ADempiere/contextMenu.js
  src/store/modules/ADempiere/utils.js
  src/views/ADempiere/Window/index.vue
Labels: Base Changes, bug

#354 Duplicate Processes
  src/store/modules/ADempiere/processControl.js
  src/views/ADempiere/ProcessActivity/index.vue
Labels: bug

#345 fix: #344 Fields that are not displayed by default and have a default value.
  src/components/ADempiere/Field/FieldSelect.vue
  src/router/modules/ADempiere/menu.js
  src/store/modules/ADempiere/browser.js
  src/store/modules/ADempiere/window.js
  src/utils/ADempiere/contextUtils.js
  src/utils/ADempiere/dictionaryUtils.js
  src/utils/ADempiere/valueUtils.js
Labels: Waiting for User Changes

#348 fix: #347 Loses values when create entity using callout generate error or warning.
  src/components/ADempiere/DataTable/menu/menuTableMixin.js
  src/store/modules/ADempiere/calloutControl.js
  src/store/modules/ADempiere/data.js
  src/store/modules/ADempiere/windowControl.js
  src/utils/ADempiere/dictionaryUtils.js
Labels: Waiting for User Changes, bug

#350 support style mode mobile
  src/components/ADempiere/ContainerInfo/recordLogs.vue
  src/views/ADempiere/Window/index.vue
Labels: UI Base Features, Waiting for User Changes, enhancement

#352 add ADempiere template to make components, views and store modules files
  plop-templates/ADempiere/component/index.hbs
  plop-templates/ADempiere/component/prompt.js
  plop-templates/ADempiere/store/index.hbs
  plop-templates/ADempiere/store/prompt.js
  plop-templates/ADempiere/view/index.hbs
  plop-templates/ADempiere/view/prompt.js
  plopfile.js
Labels: Waiting for User Changes, enhancement

#353 bugfix breadcrumb redirect action
  src/components/Breadcrumb/index.vue
Labels: Base Changes, Waiting for User Changes, bug

#357 fix: #356 Display logic field when set empty value in parent field.
  src/components/ADempiere/Field/index.vue
  src/store/modules/ADempiere/context.js
  src/store/modules/ADempiere/panel.js
  src/utils/ADempiere/evaluator.js
Labels: Waiting for User Changes, bug

#360 feat: Service routes are supported instead of individual ports.
  src/api/ADempiere/constants.js
  src/api/ADempiere/data.js
  src/api/ADempiere/dictionary.js
  src/api/ADempiere/enrollment.js
  src/api/user.js
Labels: Base Changes, enhancement

#359 Support mobile
  src/components/ADempiere/Field/chatTextLong.vue
  src/views/ADempiere/Window/index.vue
Labels: UI Base Features

#362 fix: #361 Redirect to blank page from the dashboards.
  src/components/ADempiere/Dashboard/docstatus/index.vue
  src/components/ADempiere/Dashboard/favourites/index.vue
  src/components/ADempiere/Dashboard/recentItems/index.vue
Labels: Base Changes, bug

#363 Does not sort the field list of the child tabs on every render.
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/DataTable/menu/menuTableMixin.js
  src/store/modules/ADempiere/panel.js
  src/utils/ADempiere/dictionaryUtils.js
Labels: Base Changes, bug

#369 Bugfix lookups labels
  src/components/ADempiere/Field/FieldSelect.vue
Labels: bug

#366 correct unnecessary requests
  src/views/ADempiere/Window/index.vue
Labels: UI Base Features, bug

#371 fix: #370 Lookup with NaN values in advanced query.
  src/components/ADempiere/Field/FieldSelect.vue
  src/components/ADempiere/Field/fieldPopovers/fieldContextInfo.vue
  src/components/ADempiere/Field/index.vue
  src/store/modules/ADempiere/lookup.js
  src/store/modules/ADempiere/panel.js
  src/store/modules/ADempiere/windowControl.js
  src/utils/ADempiere/dictionaryUtils.js
  src/utils/ADempiere/valueUtils.js
  src/views/ADempiere/Window/index.vue
Labels: bug

#372 add proposal for quick access from favourites dashboard in windows items
  src/components/ADempiere/Dashboard/favourites/index.vue
  src/components/ADempiere/Panel/index.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/views/ADempiere/Window/index.vue
Labels: UI Base Tools

#346 Add the workflow phases sequence
  package.json
  src/api/ADempiere/data.js
  src/components/ADempiere/Field/FieldText.vue
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/Panel/index.vue
  src/components/ADempiere/WorkflowStatusBar/index.vue
  src/main.js
  src/store/modules/ADempiere/containerInfo.js
  src/store/modules/ADempiere/contextMenu.js
  src/store/modules/ADempiere/utils.js
  src/views/ADempiere/Window/index.vue
Labels: Proposal, UI Tools, Waiting for User Changes

#375 Support in the style of Workflow Status Bar
  src/components/ADempiere/Panel/index.vue
  src/components/ADempiere/WorkflowStatusBar/index.vue
  src/views/ADempiere/Window/index.vue
Labels: UI Base Features

#374 focus only on fields that are type text and number
  src/components/ADempiere/Panel/index.vue
Labels: bug

#373 feat: Add support to environment variables.
  src/api/ADempiere/constants.js
Labels: Base Changes

#349 Add calculator component to numeric references
  src/components/ADempiere/Field/FieldNumber.vue
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/Field/popover/calculator.vue
  src/components/ADempiere/Field/popover/contextInfo.vue
  src/components/ADempiere/Field/popover/documentStatus.vue
  src/components/ADempiere/Field/popover/operatorComparison.vue
  src/components/ADempiere/Field/popover/translated.vue
  src/store/modules/ADempiere/data.js
  src/store/modules/ADempiere/panel.js
  src/utils/ADempiere/globalMethods.js
  src/utils/ADempiere/valueUtils.js
Labels: Proposal, UI Lookups, Waiting for User Changes

#379 Add demo reference
  README.md
Labels: enhancement

#376 change tabs from the path
  src/components/ADempiere/Panel/index.vue
  src/components/ADempiere/Tab/index.vue
  src/components/ADempiere/Tab/tabChildren.vue
  src/components/ADempiere/WorkflowStatusBar/index.vue
  src/store/modules/ADempiere/contextMenu.js
Labels: UI Base Features

#377 fix: Request document statuses only window is document
  src/components/ADempiere/Panel/index.vue
  src/store/modules/ADempiere/contextMenu.js
Labels: Base Changes, UI Base Tools
