Repository adempiere/adempiere-vue, pull requests merged in 2020-06, with the labels that each got.

#511 Update business data client for gRPC
  package.json
Labels: Update Library

#510 fix: Error run process, output is undefined.
  src/store/modules/ADempiere/processControl.js
Labels: Base Changes, bug

#512 increase version for library
  package.json
Labels: Update Library

#513 Just a change for pos library version to 1.3.1
  package.json
Labels: Update Library

#515 feat: Update gRPC Client packages.
  package.json
Labels: Update Library

#516 feat: Add support to package gRPC-Dictionary-Client v1.4.3.
  package.json
  src/api/ADempiere/dictionary.js
  src/store/modules/ADempiere/browser.js
  src/store/modules/ADempiere/process.js
  src/store/modules/ADempiere/window.js
  src/utils/ADempiere/dictionaryUtils.js
Labels: Update Library

#518 fix: Decimal value is NaN in requestObjectList.
  package.json
Labels: Update Library

#519 feat: Add number format value
  src/components/ADempiere/Field/FieldNumber.vue
  src/store/modules/ADempiere/data.js
  src/store/modules/user.js
  src/utils/ADempiere/references.js
  src/views/ADempiere/Test/fieldsList.js
Labels: Base Changes

#521 fix: Field number with out country and currency definition.
  src/components/ADempiere/Field/FieldNumber.vue
  src/store/modules/user.js
Labels: Base Changes, bug

#522 add global function for icons
  src/utils/ADempiere/globalMethods.js
  src/utils/ADempiere/valueUtils.js
Labels: Base Changes

#523 fix: Bad name (setSearchvalue) attribute set.
  package.json
Labels: bug

#524 Just add https page
  README.md
Labels: enhancement
