Repository adempiere/adempiere-vue, pull requests merged in 2020-05, with the labels that each got.

#477 Upgrade version for base packages
  package.json
Labels: Base Changes, Update Library

#479 fix: Icon element component.
  src/components/ADempiere/IconElement/index.vue
  src/icons/ADempiere/avatar.png
Labels: bug

#481 Fixed error with document action request for documents
  src/api/ADempiere/dashboard/dashboard.js
  src/api/ADempiere/window.js
  src/store/modules/ADempiere/contextMenu.js
Labels: bug

#482 correcting duplicate path error
  src/views/profile/components/RolesNavbar.vue
Labels: bug

#483 fix: Dashboard route path.
  src/components/ADempiere/Dashboard/calendar/index.vue
  src/components/ADempiere/Dashboard/docstatus/index.vue
  src/components/ADempiere/Dashboard/recentItems/index.vue
  src/components/ADempiere/Dashboard/userfavorites/index.vue
Labels: bug

#484 fix: Not set value without fieldList.
  src/components/ADempiere/Field/FieldMixin.js
  src/components/ADempiere/Form/index.vue
Labels: UI Lookups, bug

#488 Add support to ActionKeyPerformance event for implement enter event
  src/components/ADempiere/Field/FieldMixin.js
  src/components/ADempiere/Field/FieldText.vue
  src/components/ADempiere/Form/PriceChecking/fieldsList.js
  src/components/ADempiere/Form/PriceChecking/index.vue
  src/store/modules/ADempiere/event.js
  src/utils/ADempiere/lookupFactory.js
  src/views/ADempiere/TestView/fieldsList.js
  src/views/ADempiere/TestView/index.vue
Labels: Base Changes, enhancement

#486 fix: Empty mandatory and read only fields.
  package.json
  src/store/modules/ADempiere/calloutControl.js
  src/store/modules/ADempiere/panel.js
  src/utils/ADempiere/dictionaryUtils.js
  src/utils/ADempiere/references.js
  src/utils/ADempiere/valueUtils.js
Labels: bug

#489 Rename test view to test
  src/router/modules/ADempiere/menu.js
  src/views/ADempiere/Test/fieldsList.js
  src/views/ADempiere/Test/index.vue
Labels: enhancement

#490 feat: Add field locator warehouse
  src/api/ADempiere/field/locator.js
  src/components/ADempiere/Field/FieldLocator.vue
  src/components/ADempiere/Field/index.vue
  src/store/modules/ADempiere/data.js
  src/utils/ADempiere/references.js
Labels: UI Custom Lookups

#491 feat: Add handle focus to field.
  src/components/ADempiere/Field/FieldMixin.js
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/Panel/index.vue
  src/views/ADempiere/Test/fieldsList.js
Labels: Base Changes

#492 Add support to some translation
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/views/profile/components/RolesNavbar.vue
Labels: Improve Source Code

#494 Add support to default date format from language definition
  src/api/ADempiere/system-core.js
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/Field/popover/translated.vue
  src/filters/ADempiere/index.js
  src/filters/index.js
  src/store/getters.js
  src/store/modules/ADempiere/languageControl.js
  src/store/modules/user.js
  src/utils/ADempiere/valueFormat.js
  src/views/profile/components/RolesNavbar.vue
  src/views/profile/components/role.vue
Labels: Base Changes

#493 hide title on form
  src/views/ADempiere/Form/index.vue
Labels: Base Changes

#495 feat: Add grpc core client support.
  package.json
  src/api/ADempiere/browser.js
  src/api/ADempiere/dashboard/dashboard.js
  src/api/ADempiere/dictionary.js
  src/api/ADempiere/enrollment.js
  src/api/ADempiere/field/locator.js
  src/api/ADempiere/form/price-checking.js
  src/api/ADempiere/instances.js
  src/api/ADempiere/persistence.js
  src/api/ADempiere/private-access.js
  src/api/ADempiere/process.js
  src/api/ADempiere/report.js
  src/api/ADempiere/rule.js
  src/api/ADempiere/system-core.js
  src/api/ADempiere/values.js
  src/api/ADempiere/window.js
  src/api/user.js
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/Dialog/index.vue
  src/components/ADempiere/Panel/index.vue
  src/components/ADempiere/Tab/tabMixin.js
  src/permission.js
  src/store/modules/ADempiere/dashboard.js
  src/store/modules/ADempiere/data.js
  src/store/modules/ADempiere/languageControl.js
  src/store/modules/ADempiere/process.js
  src/store/modules/ADempiere/processControl.js
  src/store/modules/ADempiere/windowControl.js
  src/store/modules/user.js
  src/views/dashboard/admin/index.vue
Labels: Base Changes, Update Library

#496 Fixed error with unnecessary call for context
  src/utils/ADempiere/contextUtils.js
Labels: Base Changes, bug

#499 fix: Error with `this.unsubscribe is not a function`
  src/components/ADempiere/Dashboard/docstatus/index.vue
  src/components/ADempiere/Dashboard/recentItems/index.vue
  src/components/ADempiere/Dashboard/userfavorites/index.vue
  src/components/ADempiere/Form/PriceChecking/index.vue
  src/views/ADempiere/Test/index.vue
Labels: Base Changes, bug

#500 Fixed error with instance for dictionary based on new implementation …
  package.json
  src/api/ADempiere/instances.js
Labels: Update Library, bug

#501 field search bug fix in LookupFactory
  src/store/modules/ADempiere/field.js
  src/utils/ADempiere/lookupFactory.js
Labels: UI Custom Lookups, bug

#502 feat: Add grpc core client 1.0.7
  package.json
  src/api/ADempiere/instances.js
  src/api/ADempiere/system-core.js
  src/utils/ADempiere/globalMethods.js
  src/utils/ADempiere/valueUtils.js
Labels: Update Library

#503 Add support to latest version of library
  package.json
Labels: Update Library

#504 fix: Navigation duplicated.
  package.json
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/Panel/index.vue
Labels: bug

#505 Just a increase for POS version library
  package.json
Labels: Update Library

#506 Upgrade version from gRPC library
  package.json
Labels: Update Library

#507 feat: Upgrade version from gRPC library.
  package.json
Labels: Update Library
