Repository adempiere/adempiere-vue, pull requests merged in 2021-10, with the labels that each got.

#1248 Sequence Increase when Changing Price List
  src/components/ADempiere/Form/VPOS/Order/index.vue
Labels: 02 Bug, 27 Fast Resolution, (POS) Point of Sales

#1249 Add ID number in Business Partner field
  src/components/ADempiere/Form/VPOS/BusinessPartner/index.vue
  src/components/ADempiere/Form/VPOS/BusinessPartner/mixinBusinessPartner.js
Labels: 02 Bug, 27 Fast Resolution, (POS) Point of Sales

#1251 sort of the product table columns
  src/components/ADempiere/Form/VPOS/ProductInfo/productList.vue
Labels: 02 Bug, 27 Fast Resolution, (POS) Point of Sales

#1253 feat: Add values with permant link.
  src/components/ADempiere/PanelDefinition/index.vue
  src/store/modules/ADempiere/dataManager.js
  src/store/modules/ADempiere/fieldValue.js
  src/store/modules/ADempiere/panel/actions.js
  src/store/modules/ADempiere/permantLink.js
  src/utils/ADempiere/constants/actionsMenuList.js
  src/utils/ADempiere/filters.js
  src/utils/ADempiere/valueUtils.js
  src/views/ADempiere/Window/MultiTabWindow.vue
Labels: (UITL) UI Tools, 12 Feature

#1255 fix: Create record request with empty mandatory.
  src/store/modules/ADempiere/dictionary/window/getters.js
  src/store/modules/ADempiere/persistence.js
Labels: 02 Bug, (UITL) UI Tools

#1256 feat: Add support for Yarn only.
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/publish.yml
  .github/workflows/push-image.yml
  .gitignore
  .npmrc
  README.es.md
  README.md
  package-lock.json
  package.json
  yarn.lock
Labels: 01 Enhancement, (ULB) Update Library, 32 Proposal, (CI/CD) Continuous Integration/Continous Delivery, 22 dependencies

#1261 feat: Add support to yarn.
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/publish.yml
  .github/workflows/push-image.yml
  .gitignore
  README.es.md
  README.md
  package-lock.json
  package.json
  yarn.lock
Labels: (ULB) Update Library, (CI/CD) Continuous Integration/Continous Delivery, 22 dependencies

#1262 fix: Remove deprecated addRoutes
  src/permission.js
  src/settings.js
  src/store/modules/permission.js
Labels: 02 Bug, (UIBT) UI Basic Tools, (MEN) Menues
