Repository adempiere/adempiere-vue, pull requests merged in 2021-03, with the labels that each got.

#615 add tax to order
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/components/ADempiere/Form/VPOS/posMixin.js
Labels: UI Tools

#618 Verify empty fields before processing payment
  src/components/ADempiere/Form/VPOS/Collection/index.vue
  src/store/modules/ADempiere/panel/getters.js
Labels: Base Changes

#580 feat: Update repository
  .eslintrc.js
  .github/FUNDING.yml
  package.json
  src/api/user.js
  src/components/Charts/Keyboard.vue
  src/components/Charts/LineMarker.vue
  src/components/Charts/MixChart.vue
  src/components/Tinymce/index.vue
  src/lang/index.js
  src/layout/components/Navbar.vue
  src/main.js
  src/router/index.js
  src/router/modules/ADempiere/enrollment.js
  src/utils/permission.js
  src/views/components-demo/avatar-upload.vue
  src/views/components-demo/back-to-top.vue
  src/views/components-demo/sticky.vue
  src/views/components-demo/tinymce.vue
  src/views/dashboard/admin/components/BarChart.vue
  src/views/dashboard/admin/components/BoxCard.vue
  src/views/dashboard/admin/components/LineChart.vue
  src/views/dashboard/admin/components/PieChart.vue
  src/views/dashboard/admin/components/RaddarChart.vue
  src/views/documentation/index.vue
  src/views/example/components/ArticleDetail.vue
  src/views/excel/export-excel.vue
  src/views/pdf/index.vue
  src/views/permission/role.vue
  src/views/theme/index.vue
  vue.config.js
Labels: Base Changes

#633 fix calculator
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/Field/popover/calculator/index.vue
  src/store/modules/ADempiere/panel/actions.js
Labels: UI Base Tools, bug

#647 fixes #646 print console.log login data.
  src/store/modules/user.js
Labels: Minor Change

#651 Bugfix/fix last name service create business partner
  src/api/ADempiere/system-core.js
  src/components/ADempiere/Form/VPOS/BusinessPartner/businessPartnerCreate.vue
  src/components/ADempiere/Form/VPOS/BusinessPartner/fieldsListCreate.js
Labels: Fast Resolution, Point of Sales (POS), bug

#652 fix 404
  src/store/modules/permission.js
  src/store/modules/user.js
Labels: Fast Resolution, bug

#654 fix: #653 Set default values in panel with open as menu.
  src/components/ADempiere/DropdownMenu/index.vue
  src/layout/components/Sidebar/SidebarItem.vue
Labels: Base Changes, Fast Resolution

#655 Bugfix/validate private access
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/store/modules/ADempiere/data/actions.js
Labels: Fast Resolution, Security

#656 Fix sequence field location
  src/components/ADempiere/Field/FieldLocation/locationAddressForm.vue
Labels: Medium Resolution

#664 fix: Unnecessary requests for the sort type tab.
  src/store/modules/ADempiere/windowControl/actions.js
Labels: UI Base Tools

#665 action value correction in dialog when defined
  src/components/ADempiere/Dialog/index.vue
Labels: Base Changes

#669 Add default API for testing project
  config/default.json
Labels: Base Changes

#672 fixed styling of labels for select boxes in RolesNavbar
  src/views/profile/components/RolesNavbar.vue
Labels: Fast Resolution, UI Base Features

#676 fix: Is read only record with different client id.
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/Panel/mainPanelMixin.js
Labels: Base Changes, Fast Resolution, bug

#677 Remove unnecessary lines
  .github/workflows/publish.yml
Labels: Continuous Integration(CI), Fast Resolution

#678 Improve display for locator component
  src/api/ADempiere/field/locator.js
  src/components/ADempiere/Field/FieldLocator.vue
Labels: Fast Resolution, UI Lookups

#662 Support to Field Preference
  src/api/ADempiere/field/preference.js
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/Field/popover/preference/filelistPreference.js
  src/components/ADempiere/Field/popover/preference/index.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/utils/ADempiere/valueUtils.js
  src/views/login/index.vue
Labels: Medium Resolution, UI Base Features

#670 Support Binary
  src/api/ADempiere/field/binary.js
  src/components/ADempiere/Field/FieldImage.vue
Labels: Base Changes, Medium Resolution, UI Base Features

#680 Fixed error with Search Product from Value instead name
  src/components/ADempiere/Form/VPOS/KeyLayout/index.vue
  src/utils/ADempiere/apiConverts/pos.js
Labels: Fast Resolution, Point of Sales (POS), bug

#682 Feature/#pos rename functions
  src/api/ADempiere/form/point-of-sales.js
  src/components/ADempiere/Form/ProductInfo/productList.vue
  src/components/ADempiere/Form/VPOS/Collection/index.vue
  src/components/ADempiere/Form/VPOS/KeyLayout/index.vue
  src/components/ADempiere/Form/VPOS/Options/index.vue
  src/store/modules/ADempiere/pointOfSales/listProductPrice.js
  src/store/modules/ADempiere/pointOfSales/payments/actions.js
Labels: Fast Resolution, Improve Source Code

#681 Tests fo badge component
  tests/unit/components/ADempiere/Badge/index.vue.spec.js
  tests/unit/components/Hamburger.spec.js
  tests/unit/components/SvgIcon.spec.js
Labels: Medium Resolution, Unit Test

#679 Popover List Product Info
  src/components/ADempiere/Form/VPOS/Options/index.vue
  src/components/ADempiere/Form/VPOS/ProductInfo/index.vue
Labels: Fast Resolution, UI Base Features

#683 Rename functions for location components
  src/api/ADempiere/field/location.js
  src/components/ADempiere/Field/FieldLocation/index.vue
  src/components/ADempiere/Field/FieldLocation/locationAddressForm.vue
  src/components/ADempiere/Field/FieldLocation/mixinLocation.js
Labels: Fast Resolution, Improve Source Code, Minor Change

#684 Validate if the field has a callout before updating or creating
  src/components/ADempiere/Field/mixin/mixinField.js
  src/store/modules/ADempiere/calloutControl.js
  src/store/modules/ADempiere/panel/actions.js
Labels: Base Changes, Fast Resolution

#671 Support Private Access
  src/api/ADempiere/private-access.js
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/Dialog/index.vue
  src/components/ADempiere/recordAccess/index.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/accessRecord.js
Labels: Medium Resolution, Security, Waiting for Definition

#685 add validate the IsProcessed
  src/components/ADempiere/Form/VPOS/BusinessPartner/businessPartnerCreate.vue
  src/components/ADempiere/Form/VPOS/BusinessPartner/index.vue
  src/components/ADempiere/Form/VPOS/Collection/index.vue
  src/components/ADempiere/Form/VPOS/KeyLayout/index.vue
  src/components/ADempiere/Form/VPOS/Options/index.vue
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/components/ADempiere/Form/VPOS/OrderList/index.vue
  src/components/ADempiere/Form/VPOS/posMixin.js
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/pointOfSales/order/getters.js
  src/store/modules/ADempiere/utils.js
Labels: Base Changes, Fast Resolution

#694 Change Button the Chat
  src/components/ADempiere/ChatEntries/index.vue
Labels: Base Changes, enhancement

#693 fix: Field isActive not edit with false value.
  src/components/ADempiere/DataTable/dataTables-Script.js
  src/components/ADempiere/Field/FieldYesNo.vue
  src/store/modules/ADempiere/panel/actions.js
  src/utils/ADempiere/references.js
Labels: Fast Resolution, UI Base Features, bug

#696 Feature: Add preference service
  src/api/ADempiere/field/preference.js
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/Field/popover/preference/index.vue
  src/components/ADempiere/Field/popover/preference/preferenceFields.js
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/utils/ADempiere/valueUtils.js
Labels: UI Base Features, enhancement

#695 fix: Report change print format.
  src/store/modules/ADempiere/processDefinition.js
  src/store/modules/ADempiere/report.js
  src/utils/ADempiere/apiConverts/report.js
Labels: Medium Resolution, UI Base Tools, bug

#699 fix: Empty mandatory fields.
  src/store/modules/ADempiere/panel/getters.js
  src/store/modules/ADempiere/windowControl/actions.js
Labels: Base Changes, Fast Resolution, bug

#700 Bugfix/#692 context menu butons
  src/components/ADempiere/ContextMenu/contextMenuDesktop.vue
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/ContextMenu/contextMenuMobile.vue
  src/components/ADempiere/ContextMenu/index.vue
  src/components/ADempiere/RightPanel/index.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/contextMenu.js
  src/views/ADempiere/Window/index.vue
Labels: Medium Resolution, UI Base Features
