Repository adempiere/adempiere-vue, pull requests merged in 2021-01, with the labels that each got.

#565 Price Checking
  src/components/ADempiere/Form/PriceChecking/index.vue
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/components/ADempiere/Form/VPOS/Order/orderLineMixin.js
Labels: enhancement

#563 feat: Refactor process vuex module.
  src/store/modules/ADempiere/process.js
  src/store/modules/ADempiere/process/actions.js
  src/store/modules/ADempiere/process/getters.js
  src/store/modules/ADempiere/process/index.js
  src/store/modules/ADempiere/process/mutations.js
  src/store/modules/ADempiere/process/state.js
  src/store/modules/ADempiere/report.js
  src/utils/ADempiere/exportUtil.js
  src/views/ADempiere/ReportViewer/index.vue
Labels: Improve Source Code

#564 feat: Add icon in header search component.
  src/components/HeaderSearch/index.vue
Labels: UI Base Tools

#566 add quantityAvailable
  src/components/ADempiere/Form/ProductInfo/productList.vue
Labels: UI Lookups

#567 correcting field title errors
  src/components/ADempiere/Field/FieldLocation/fieldsList.js
  src/components/ADempiere/Form/VPOS/BusinessPartner/fieldsListCreate.js
  src/components/ADempiere/Form/VPOS/BusinessPartner/fieldsListSearch.js
Labels: UI Base Features

#573 Correcting scroll error and empty left panel
  src/components/ADempiere/DataTable/dataTables-Script.js
  src/components/ADempiere/Form/PriceChecking/index.vue
  src/views/ADempiere/Window/index.vue
Labels: UI Base Features, UI Lookups

#568 Validate collection
  src/components/ADempiere/Form/VPOS/BusinessPartner/businessPartnersList.vue
  src/components/ADempiere/Form/VPOS/BusinessPartner/fieldsListSearch.js
  src/components/ADempiere/Form/VPOS/Collection/fieldsListCollection.js
  src/components/ADempiere/Form/VPOS/Collection/index.vue
  src/components/ADempiere/Form/VPOS/ProductInfo/index.vue
  src/components/RightPanel/index.vue
  src/components/RightPanel/menu.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/pointOfSales/collection.js
  src/utils/ADempiere/apiConverts/core.js
Labels: UI Base Features

#570 Add Mnemonic Command
  src/components/ADempiere/Form/VPOS/Collection/fieldsListCollection.js
  src/components/ADempiere/Form/VPOS/Order/fieldsListOrder.js
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/components/ADempiere/Form/VPOS/ProductInfo/fieldsList.js
  src/components/ADempiere/Form/VPOS/ProductInfo/index.vue
  src/components/ADempiere/Form/VPOS/posMixin.js
Labels: Base Changes

#575 Errors in fields and when creating lines
  src/components/ADempiere/Dialog/index.vue
  src/components/ADempiere/Field/FieldTextLong.vue
  src/components/ADempiere/Field/index.vue
  src/store/modules/ADempiere/data/actions.js
Labels: Base Changes

#576 Add focus to Price Query
  src/components/ADempiere/Form/PriceChecking/index.vue
Labels: bug
