Repository adempiere/adempiere-vue, pull requests merged in 2021-02, with the labels that each got.

#577 Feature/support pos
  src/components/ADempiere/Form/VPOS/Collection/convertAmount/index.vue
  src/components/ADempiere/Form/VPOS/Collection/fieldsListCollection.js
  src/components/ADempiere/Form/VPOS/Collection/index.vue
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/components/ADempiere/Form/VPOS/OrderList/index.vue
  src/store/modules/ADempiere/pointOfSales/collection.js
Labels: Base Changes, UI Base Features

#578 support for payment methods
  src/api/ADempiere/form/point-of-sales.js
  src/components/ADempiere/Form/VPOS/Collection/index.vue
  src/components/ADempiere/Form/VPOS/Collection/typeCollection.vue
  src/components/ADempiere/Form/VPOS/Options/index.vue
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/components/ADempiere/Form/VPOS/OrderList/index.vue
  src/store/modules/ADempiere/pointOfSales/collection.js
  src/utils/ADempiere/apiConverts/pos.js
Labels: UI Custom Lookups, enhancement

#581 Find Current Lenguage Definition
  src/utils/ADempiere/valueFormat.js
Labels: Base Changes

#582 error correction with default point of sale with sales representative
  src/components/ADempiere/Form/PriceChecking/index.vue
  src/store/modules/ADempiere/pointOfSales/index.js
Labels: Base Changes, Update Library

#583 Point of Sale Processes
  src/api/ADempiere/form/point-of-sales.js
  src/components/ADempiere/Dialog/index.vue
  src/components/ADempiere/Form/VPOS/Options/index.vue
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/components/ADempiere/Form/VPOS/OrderList/index.vue
  src/components/ADempiere/Form/VPOS/posMixin.js
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/pointOfSales/collection.js
  src/store/modules/ADempiere/pointOfSales/index.js
  src/store/modules/ADempiere/pointOfSales/order.js
  src/store/modules/ADempiere/process/actions.js
  src/store/modules/ADempiere/utils.js
  src/utils/ADempiere/constants/posProcess.js
  src/views/ADempiere/Form/index.vue
Labels: Base Changes

#586 feat: Refactor payments vuex module
  package.json
  src/components/ADempiere/Form/VPOS/Collection/index.vue
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/components/ADempiere/Form/VPOS/OrderList/index.vue
  src/store/modules/ADempiere/pointOfSales/collection.js
  src/store/modules/ADempiere/pointOfSales/order.js
  src/store/modules/ADempiere/pointOfSales/payments/actions.js
  src/store/modules/ADempiere/pointOfSales/payments/getters.js
  src/store/modules/ADempiere/pointOfSales/payments/index.js
  src/store/modules/ADempiere/pointOfSales/payments/mutations.js
  src/store/modules/ADempiere/pointOfSales/payments/state.js
Labels: UI Base Features, UI Base Tools

#587 Add support to GH Actions
  .github/workflows/publish.yml
  .travis.yml
  README.md
Labels: Continuous Integration(CI)

#602 Change icon when running in mobile mode
  src/components/ADempiere/ContextMenu/contextMenuMobile.vue
Labels: Base Changes, UI Base Features

#606 fix point of sale not found
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/components/ADempiere/Form/VPOS/posMixin.js
Labels: bug

#607 fix search recient Items and Document tasks
  src/components/ADempiere/Dashboard/docstatus/index.vue
  src/components/ADempiere/Dashboard/mixinDashboard.js
  src/components/ADempiere/Dashboard/recentItems/index.vue
  src/components/ADempiere/Dashboard/userfavorites/index.vue
Labels: UI Base Features, bug
