Repository adempiere/adempiere-vue, pull requests merged in 2021-06, with the labels that each got.

#893 Mobile Point of Sale Support
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/components/ADempiere/Form/VPOS/index.vue
  src/components/ADempiere/Form/VPOS/templateDevice/desktop.vue
  src/components/ADempiere/Form/VPOS/templateDevice/mobile.vue
Labels: Fast Resolution, Point of Sales (POS), Proposal

#892 Forms
  docs/.vuepress/config.js
  docs/.vuepress/public/images/forms/point-of-sales/add-business-partner.gif
  docs/.vuepress/public/images/forms/point-of-sales/add-product-with-catalog.gif
  docs/.vuepress/public/images/forms/point-of-sales/add-product-with-code-or-name.gif
  docs/.vuepress/public/images/forms/point-of-sales/add-product-with-code-reader.gif
  docs/.vuepress/public/images/forms/point-of-sales/change-point-of-sale-terminal.gif
  docs/.vuepress/public/images/forms/point-of-sales/collect-the-order.gif
  docs/.vuepress/public/images/forms/point-of-sales/create-business-partner.png
  docs/.vuepress/public/images/forms/point-of-sales/create-new-order.gif
  docs/.vuepress/public/images/forms/point-of-sales/option-create-new-order.png
  docs/.vuepress/public/images/forms/point-of-sales/position-yourself-on-the-order-lines.gif
  docs/.vuepress/public/images/forms/point-of-sales/remove-the-order-line.gif
  docs/.vuepress/public/images/forms/point-of-sales/sales-order-information.png
  docs/.vuepress/public/images/forms/point-of-sales/sales-order-lines.gif
  docs/.vuepress/public/images/forms/point-of-sales/sales-order-lines.png
  docs/es/guide/forms/point-of-sales.md
  docs/guide/forms/point-of-sales.md
  docs/zh/guide/forms/point-of-sales.md
Labels: Documentation (Doc), Point of Sales (POS)

#895 Fix error when closing popover of amount to be converted
  src/components/ADempiere/Form/VPOS/Collection/convertAmount/fieldsListConvertAmountCollection.js
  src/components/ADempiere/Form/VPOS/Collection/convertAmount/index.vue
  src/components/ADempiere/Form/VPOS/Order/index.vue
Labels: Fast Resolution, Minor Change, Point of Sales (POS), bug

#897 Add the link to the documentation of the repositories.
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/views/documentation/index.vue
Labels: Documentation (Doc), Minor Change, Proposal

#901 fix translation in product information
  src/lang/ADempiere/es.js
Labels: Fast Resolution, Minor Change

#889 fix: Load Smart Browser.
  src/api/ADempiere/browser.js
  src/components/ADempiere/DataTable/dataTables-Script.js
  src/store/modules/ADempiere/browserDefinition.js
  src/utils/ADempiere/apiConverts/dictionary.js
Labels: Base Changes, UI Tools, bug, help wanted

#904 feat: Update adempiere proxy with redis config.
  docker-compose.yaml
Labels: Continuous Integration(CI)

#906 feat: Window refefinition
  config/default.json
  src/utils/ADempiere/dictionaryUtils.js
  src/views/ADempiere/WindowView/DocumentWindow.vue
  src/views/ADempiere/WindowView/StandardWindow.vue
  src/views/ADempiere/WindowView/index.vue
Labels: Base Changes

#907 Feature/add endpoint setup
  config/default.json
  src/api/ADempiere/form/point-of-sales.js
  src/api/ADempiere/form/price-checking.js
  src/components/ADempiere/Form/BarcodeReader/index.vue
  src/components/ADempiere/Form/PriceChecking/index.vue
  src/components/ADempiere/Form/VPOS/Options/index.vue
  src/components/ADempiere/Form/VPOS/Order/orderLineMixin.js
  src/components/ADempiere/Form/VPOS/posMixin.js
  src/store/modules/ADempiere/pointOfSales/order/actions.js
  src/store/modules/ADempiere/pointOfSales/orderLine/actions.js
  src/store/modules/ADempiere/pointOfSales/point/actions.js
Labels: Improve Source Code, Minor Change

#905 Point of Sale Guide
  src/components/ADempiere/Form/VPOS/Collection/index.vue
  src/components/ADempiere/Form/VPOS/Guide/steps.js
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/components/ADempiere/Form/VPOS/templateDevice/desktop.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/layout/components/Navbar.vue
Labels: Documentation (Doc), Point of Sales (POS), Proposal, enhancement

#909 Styling fixes
  src/components/ADempiere/Field/FieldDate.vue
  src/components/ADempiere/Field/FieldLocator.vue
  src/components/ADempiere/Field/FieldNumber.vue
  src/components/ADempiere/Field/FieldOptions/LabelField.vue
  src/components/ADempiere/Field/FieldOptions/LabelPopoverOption.vue
  src/components/ADempiere/Field/FieldOptions/contextInfo/index.vue
  src/components/ADempiere/Field/FieldOptions/index.vue
  src/components/ADempiere/Field/FieldSelect.vue
  src/components/ADempiere/Field/FieldSelectMultiple.vue
  src/components/ADempiere/Field/FieldText.vue
  src/components/ADempiere/Field/FieldYesNo.vue
  src/components/ADempiere/Field/index.vue
Labels: Base Changes, Fast Resolution, enhancement

#908 error loading window
  src/views/ADempiere/Window/windowLogicComponent.js
Labels: Fast Resolution, bug

#912 fix iSOcode pos
  src/components/ADempiere/Form/VPOS/Order/line/index.vue
Labels: Base Changes, Point of Sales (POS)

#910 support to quick guide
  src/components/ADempiere/Field/index.vue
  src/layout/components/Navbar.vue
Labels: Minor Change, Proposal

#911 Feature/add column pos
  src/components/ADempiere/Form/VPOS/Order/orderLineMixin.js
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/pointOfSales/payments/actions.js
Labels: Fast Resolution, Point of Sales (POS)

#914 Fix Check Price
  src/components/ADempiere/Form/PriceChecking/index.vue
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/components/ADempiere/Form/VPOS/ProductInfo/index.vue
Labels: Fast Resolution, Point of Sales (POS)

#915 Inserted line breaks in side menu
  src/components/ADempiere/Field/index.vue
  src/layout/components/Sidebar/Item.vue
  src/styles/sidebar.scss
Labels: UI Base Features

#916 Remove bugs from POS implementation
  src/api/ADempiere/form/point-of-sales.js
  src/api/ADempiere/form/price-checking.js
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/components/ADempiere/Form/VPOS/Order/orderLineMixin.js
  src/lang/ADempiere/en.js
  src/store/modules/ADempiere/pointOfSales/getters/index.js
  src/store/modules/ADempiere/pointOfSales/point/actions.js
  src/store/modules/ADempiere/pointOfSales/point/mutations.js
  src/store/modules/ADempiere/pointOfSales/point/state.js
  src/store/modules/ADempiere/pointOfSales/productPrice/actions.js
Labels: Point of Sales (POS), bug

#920 feat: Browser redefinition.
  config/default.json
  src/utils/ADempiere/dictionaryUtils.js
  src/views/ADempiere/BrowserView/index.vue
Labels: Improve Source Code, Proposal, enhancement

#922 Feature/rename pos objects
  src/components/ADempiere/Form/VPOS/Collection/index.vue
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/components/ADempiere/Form/VPOS/posMixin.js
  src/components/ADempiere/Form/VPOS/templateDevice/desktop.vue
  src/components/ADempiere/Form/VPOS/templateDevice/mobile.vue
  src/store/modules/ADempiere/pointOfSales/getters/index.js
  src/store/modules/ADempiere/pointOfSales/payments/actions.js
  src/store/modules/ADempiere/pointOfSales/point/actions.js
  src/store/modules/ADempiere/pointOfSales/point/mutations.js
  src/store/modules/ADempiere/pointOfSales/point/state.js
Labels: Improve Source Code, Point of Sales (POS)

#923 Error when minimizing the sidebar
  src/layout/components/Sidebar/SidebarItem.vue
Labels: bug

#924 feat: Add standard method to is displayed field/column
  src/components/ADempiere/DataTable/dataTables-Script.js
  src/components/ADempiere/DataTable/filterColumns.vue
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/Field/index.vue
  src/store/modules/ADempiere/panel/actions.js
  src/store/modules/ADempiere/panel/getters.js
  src/utils/ADempiere/dictionaryUtils.js
Labels: Base Changes, Improve Source Code, Proposal

#927 Adjust fields when opening the registration navigation
  src/components/ADempiere/Field/index.vue
  src/utils/ADempiere/references.js
Labels: Fast Resolution, bug

#919 feat: Separate record-lock in different tab component.
  src/components/ADempiere/ContainerOptions/LockRecord/index.vue
  src/components/ADempiere/Tab/index.vue
Labels: Improve Source Code, Proposal

#926 Bugreport918 vertical spacing in side menu
  src/layout/components/Sidebar/Item.vue
  src/layout/components/Sidebar/SidebarItem.vue
  src/layout/components/Sidebar/index.vue
  src/styles/sidebar.scss
Labels: bug

#929 Support Document Type
  src/api/ADempiere/form/point-of-sales.js
  src/components/ADempiere/Form/VPOS/Order/fieldsListOrder.js
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/components/ADempiere/Form/VPOS/posMixin.js
  src/store/modules/ADempiere/pointOfSales/order/actions.js
Labels: Fast Resolution, Point of Sales (POS)

#931 feat: Unify FilterField and FilterColumn component
  src/components/ADempiere/DataTable/dataTables-Script.js
  src/components/ADempiere/DataTable/dataTables-StyleScoped.scss
  src/components/ADempiere/DataTable/filterColumns.vue
  src/components/ADempiere/DataTable/index.vue
  src/components/ADempiere/FilterFields/index.vue
  src/store/modules/ADempiere/panel/getters.js
Labels: Fast Resolution, Improve Source Code, Proposal, UI Custom Lookups

#930 support price checking
  src/components/ADempiere/Form/PriceChecking/index.vue
Labels: Point of Sales (POS)

#938 Add support to dashboard as chart
  src/api/ADempiere/dashboard/dashboard.js
  src/components/ADempiere/Dashboard/index.vue
  tests/unit/utils/ADempiere/apiConverts/objects/converted/dashboard.json
Labels: Base Changes

#937 Auto-Complete field support
  src/components/ADempiere/Field/FieldAutocomplete.vue
Labels: Fast Resolution, UI Lookups

#939 Add chart support from ADempiere
  src/api/ADempiere/dashboard/chart.js
  src/components/ADempiere/Dashboard/charts/BarChart.vue
  src/components/ADempiere/Dashboard/charts/LineChart.vue
  src/components/ADempiere/Dashboard/charts/PieChart.vue
  src/components/ADempiere/Dashboard/charts/RaddarChart.vue
  src/components/ADempiere/Dashboard/charts/mixins/resize.js
  src/components/ADempiere/Dashboard/index.vue
  src/store/modules/ADempiere/dashboard.js
Labels: UI Base Tools, enhancement

#936 Add Day Rate
  src/components/ADempiere/Form/PriceChecking/index.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/pointOfSales/payments/actions.js
Labels: Fast Resolution, Minor Change

#921 feat: Refactor documentation view.
  src/views/documentation/RepositoryDocumentation.vue
  src/views/documentation/RepositoryTags.vue
  src/views/documentation/index.vue
Labels: Proposal, enhancement

#934 feat: Test Views from views redefinition
  src/components/ADempiere/PanelDefinition/StandardPanel.vue
  src/components/ADempiere/PanelDefinition/UnsupportedPanel.vue
  src/components/ADempiere/PanelDefinition/index.vue
  src/router/modules/ADempiere/menu.js
  src/router/modules/ADempiere/staticRoutes.js
  src/router/modules/ADempiere/testRoutes.js
  src/utils/ADempiere/dictionaryUtils.js
  src/views/ADempiere/BrowserView/index.vue
  src/views/ADempiere/ProcessView/index.vue
  src/views/ADempiere/Test/Process/index.vue
  src/views/ADempiere/Test/SmartBrowser/index.vue
  src/views/ADempiere/WindowView/DocumentWindow.vue
  src/views/ADempiere/WindowView/StandardWindow.vue
  src/views/ADempiere/WindowView/index.vue
Labels: Medium Resolution, UI Lookups

#940 fix: Process logs request duplicated
  src/store/modules/ADempiere/process/actions.js
  src/store/modules/ADempiere/process/getters.js
  src/store/modules/ADempiere/process/mutations.js
  src/store/modules/ADempiere/process/state.js
  src/store/modules/ADempiere/processLog.js
  src/utils/ADempiere/apiConverts/process.js
  src/views/ADempiere/ProcessActivity/index.vue
  src/views/ADempiere/ProcessActivity/modeDesktop.vue
  src/views/ADempiere/ProcessActivity/modeMobile.vue
  src/views/ADempiere/ProcessActivity/processActivity.js
Labels: Base Changes

#941 fix: Lock record get values with router
  src/components/ADempiere/ContainerOptions/LockRecord/index.vue
  src/components/ADempiere/Tab/index.vue
Labels: Base Changes

#942 feat: Add default table to replace data table.
  src/components/ADempiere/DefaultTable/CellInfo.vue
  src/components/ADempiere/DefaultTable/index.vue
  src/utils/ADempiere/references.js
  src/views/ADempiere/BrowserView/index.vue
Labels: Long Resolution, Proposal, UI Tools

#948 Add multiTab route
  src/router/modules/ADempiere/testRoutes.js
  src/views/ADempiere/Test/MultiTabWindow/index.vue
  src/views/ADempiere/Test/MultiTabWindow/multiTabWindow.json
Labels: Base Changes

#949 Fixed tab number for new window definition
  src/components/ADempiere/TabManager/index.vue
Labels: Base Changes, bug

#950 Change tab property name for Tab Manager
  src/components/ADempiere/TabManager/index.vue
Labels: Base Changes

#947 fix size dashboard
  src/components/ADempiere/Dashboard/calendar/index.vue
  src/components/ADempiere/Dashboard/charts/AreaChart.vue
  src/components/ADempiere/Dashboard/charts/BarChart.vue
  src/components/ADempiere/Dashboard/charts/LineChart.vue
  src/components/ADempiere/Dashboard/charts/PieChart.vue
  src/components/ADempiere/Dashboard/charts/RaddarChart.vue
  src/components/ADempiere/Dashboard/charts/WaterfallChart.vue
  src/components/ADempiere/Dashboard/docstatus/index.vue
  src/components/ADempiere/Dashboard/recentItems/index.vue
  src/components/ADempiere/Dashboard/userfavorites/index.vue
Labels: Fast Resolution

#958 Add callback functions
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/Field/mixin/mixinField.js
  src/components/ADempiere/PanelDefinition/StandardPanel.vue
  src/components/ADempiere/PanelDefinition/index.vue
  src/components/ADempiere/TabManager/index.vue
  src/store/modules/ADempiere/panel/actions.js
  src/views/ADempiere/Test/MultiTabWindow/index.vue
  src/views/ADempiere/WindowView/StandardWindow.vue
  src/views/ADempiere/WindowView/index.vue
Labels: Base Changes

#954 Style Dashboard
  src/components/ADempiere/Dashboard/calendar/index.vue
  src/components/ADempiere/Dashboard/charts/AreaChart.vue
  src/components/ADempiere/Dashboard/charts/BarChart.vue
  src/components/ADempiere/Dashboard/charts/LineChart.vue
  src/components/ADempiere/Dashboard/charts/PieChart.vue
  src/components/ADempiere/Dashboard/charts/RaddarChart.vue
  src/components/ADempiere/Dashboard/charts/WaterfallChart.vue
  src/components/ADempiere/Dashboard/docstatus/index.vue
  src/components/ADempiere/Dashboard/index.vue
  src/components/ADempiere/Dashboard/recentItems/index.vue
  src/components/ADempiere/Dashboard/userfavorites/index.vue
  src/store/modules/ADempiere/dashboard.js
  src/views/dashboard/admin/index.vue
Labels: Dashboard, enhancement

#956 Add Carousel Component
  src/components/ADempiere/Carousel/index.vue
Labels: Proposal, UI Base Features, UI Base Tools
