Repository adempiere/adempiere-vue, pull requests merged in 2021-04, with the labels that each got.

#704 changing the style of the new command button
  src/components/ADempiere/Form/VPOS/Order/index.vue
Labels: Fast Resolution, Point of Sales (POS), enhancement

#710 fix: Window references.
  src/components/ADempiere/Panel/mainPanelMixin.js
  src/store/modules/ADempiere/windowControl/getters.js
Labels: Base Changes, Medium Resolution, bug

#709 fix: Displayed value current document status in workflow bar.
  src/components/ADempiere/WorkflowStatusBar/index.vue
Labels: Fast Resolution, UI Lookups, bug

#712 Improve request util
  .github/workflows/publish.yml
  config/default.json
  src/api/ADempiere/browser.js
  src/api/ADempiere/dashboard/dashboard.js
  src/api/ADempiere/dictionary.js
  src/api/ADempiere/enrollment.js
  src/api/ADempiere/field/preference.js
  src/api/ADempiere/form/point-of-sales.js
  src/api/ADempiere/form/price-checking.js
  src/api/ADempiere/persistence.js
  src/api/ADempiere/private-access.js
  src/api/ADempiere/process.js
  src/api/ADempiere/report.js
  src/api/ADempiere/rule.js
  src/api/ADempiere/system-core.js
  src/api/ADempiere/user-interface.js
  src/api/ADempiere/values.js
  src/api/ADempiere/window.js
  src/api/documentation/releases.js
  src/api/role.js
  src/api/user.js
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/utils/ADempiere/request.js
  src/utils/request.js
  src/views/documentation/index.vue
Labels: Base Changes, Fast Resolution, enhancement

#716 Document Support
  config/default.json
  src/api/documentation/documentation.js
  src/views/documentation/index.vue
  src/views/documentation/tags/index.vue
Labels: Base Changes, UI Base Features, enhancement

#717 Add cursor pointer to Recient Item and Document Status table
  src/components/ADempiere/Dashboard/docstatus/index.vue
  src/components/ADempiere/Dashboard/recentItems/index.vue
Labels: Base Changes, enhancement

#705 add context menu field mode mobile
  src/components/ADempiere/ContextMenu/contextMenuDesktop.vue
  src/components/ADempiere/ContextMenu/index.vue
  src/components/ADempiere/Field/contextMenuField/calculator/buttons.js
  src/components/ADempiere/Field/contextMenuField/calculator/index.vue
  src/components/ADempiere/Field/contextMenuField/contextInfo/index.vue
  src/components/ADempiere/Field/contextMenuField/preference/index.vue
  src/components/ADempiere/Field/contextMenuField/preference/preferenceFields.js
  src/components/ADempiere/Field/contextMenuField/translated/index.vue
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/RightPanel/index.vue
  src/components/RightPanel/index.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/layout/components/Settings/index.vue
  src/store/modules/ADempiere/contextMenu.js
  src/views/ADempiere/Window/index.vue
  src/views/ADempiere/Window/windowLogicComponent.js
  src/views/profile/index.vue
Labels: Fast Resolution, UI Base Features

#722 correcting error in quantities
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/components/ADempiere/Form/VPOS/Order/line/index.vue
Labels: Point of Sales (POS)

#718 Correct Point Of Sale Alerts
  src/components/ADempiere/Form/ProductInfo/productList.vue
  src/components/ADempiere/Form/VPOS/ProductInfo/productList.vue
Labels: Point of Sales (POS)

#725 Validate mandatory fields when creating a business partner
  src/components/ADempiere/Field/FieldLocation/fieldsList.js
  src/components/ADempiere/Field/FieldLocation/locationAddressForm.vue
  src/components/ADempiere/Form/VPOS/BusinessPartner/businessPartnerCreate.vue
  src/components/ADempiere/Form/VPOS/BusinessPartner/fieldsListCreate.js
Labels: Point of Sales (POS)

#734 clean payment list
  src/components/ADempiere/Form/VPOS/Order/index.vue
Labels: Point of Sales (POS), enhancement

#737 Feture/support menu field
  src/components/ADempiere/Field/index.vue
Labels: Base Changes, Fast Resolution, UI Base Features, enhancement

#744 remove image the api documentation
  config/default.json
Labels: bug

#745 Add link to releases
  src/views/documentation/index.vue
Labels: Base Changes

#740 support search table mode mobile
  src/components/ADempiere/DataTable/dataTables-Script.js
  src/components/ADempiere/DataTable/index.vue
Labels: UI Base Features, UI Base Tools

#746 fix errors in the fields of the mobile interface with long names
  src/components/ADempiere/Field/contextMenuField/contextInfo/index.vue
  src/components/ADempiere/Field/index.vue
Labels: UI Base Features

#758 adaptable to different types of screens
  src/components/ADempiere/Form/VPOS/Order/index.vue
Labels: Point of Sales (POS)

#764 Change timeout by default
  config/default.json
Labels: Minor Change

#750 get the currency code to be paid
  src/components/ADempiere/Field/FieldNumber.vue
  src/components/ADempiere/Form/VPOS/Collection/index.vue
  src/components/ADempiere/Form/VPOS/Collection/typeCollection.vue
  src/components/ADempiere/Form/VPOS/Options/index.vue
  src/components/ADempiere/Form/VPOS/Order/fieldsListOrder.js
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/store/modules/ADempiere/pointOfSales/payments/actions.js
  src/store/modules/ADempiere/pointOfSales/payments/getters.js
  src/store/modules/ADempiere/pointOfSales/payments/mutations.js
  src/store/modules/ADempiere/pointOfSales/payments/state.js
  src/utils/ADempiere/valueUtils.js
Labels: Point of Sales (POS)

#767 Add calculator in the point of sale amount field
  src/components/ADempiere/Field/contextMenuField/calculator/index.vue
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/Form/VPOS/Collection/fieldsListCollection.js
Labels: Fast Resolution, Point of Sales (POS)

#755 record access mode mobile support
  src/components/ADempiere/ContextMenu/contextMenuDesktop.vue
  src/components/ADempiere/ContextMenu/contextMenuMobile.vue
  src/components/ADempiere/Dialog/index.vue
  src/components/ADempiere/Field/index.vue
  src/components/ADempiere/RecordAccess/index.vue
  src/components/ADempiere/RecordAccess/recordAccessDesktop.vue
  src/components/ADempiere/RecordAccess/recordAccessMobile.vue
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/contextMenu.js
  src/views/ADempiere/Window/index.vue
  src/views/ADempiere/Window/windowLogicComponent.js
Labels: UI Base Tools, bug

#762 Add sub-menu to context menu
  src/components/ADempiere/ContextMenu/contextMenuDesktop.vue
Labels: Fast Resolution, bug

#749 Converting for payment methods
  src/components/ADempiere/Form/VPOS/Collection/fieldsListCollection.js
  src/components/ADempiere/Form/VPOS/Collection/index.vue
  src/components/ADempiere/Form/VPOS/Collection/typeCollection.vue
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/components/ADempiere/Form/VPOS/posMixin.js
  src/store/modules/ADempiere/pointOfSales/payments/actions.js
  src/store/modules/ADempiere/pointOfSales/payments/getters.js
  src/store/modules/ADempiere/pointOfSales/payments/mutations.js
  src/store/modules/ADempiere/pointOfSales/payments/state.js
  src/store/modules/ADempiere/pointOfSales/point/actions.js
  src/utils/ADempiere/apiConverts/core.js
  src/utils/ADempiere/globalMethods.js
  src/utils/ADempiere/valueUtils.js
Labels: Point of Sales (POS)

#775 style context menu the field
  src/components/ADempiere/ContextMenu/contextMenuDesktop.vue
  src/components/ADempiere/ContextMenu/contextMenuMobile.vue
  src/components/ADempiere/Field/index.vue
Labels: Base Changes, Fast Resolution

#779 Error List Order
  src/components/ADempiere/Form/VPOS/OrderList/fieldsListOrders.js
  src/components/ADempiere/Form/VPOS/OrderList/index.vue
Labels: Point of Sales (POS), bug

#776 add popover for pin in the point of sales
  src/components/ADempiere/Form/VPOS/Order/line/fieldsListLine.js
  src/components/ADempiere/Form/VPOS/Order/line/index.vue
Labels: Base Changes, Point of Sales (POS), Proposal

#781 shading in the table when selecting mobile mode
  src/components/ADempiere/Dashboard/docstatus/index.vue
  src/components/ADempiere/Dashboard/recentItems/index.vue
Labels: UI Base Features

#783 add validation the isDisplayedGrid to table
  src/components/ADempiere/ContextMenu/contextMenuDesktop.vue
  src/components/ADempiere/ContextMenu/contextMenuMixin.js
  src/components/ADempiere/ContextMenu/contextMenuMobile.vue
  src/components/ADempiere/DataTable/dataTables-Script.js
Labels: Base Changes

#784 convert the values to be sent and delete unnecessary console.logs
  src/components/ADempiere/Form/VPOS/Collection/index.vue
  src/components/ADempiere/Form/VPOS/OrderList/index.vue
  src/store/modules/ADempiere/pointOfSales/order/actions.js
  src/store/modules/ADempiere/pointOfSales/payments/actions.js
  src/utils/ADempiere/globalMethods.js
  src/utils/ADempiere/valueUtils.js
Labels: Improve Source Code, Minor Change

#785 scroll in context menu
  src/components/ADempiere/ContextMenu/contextMenuDesktop.vue
Labels: Improve Source Code, enhancement

#786 style context menu
  src/components/ADempiere/ContextMenu/contextMenuDesktop.vue
Labels: Functional Test, enhancement

#788 Fix copyOrder
  src/components/ADempiere/Dialog/index.vue
  src/components/ADempiere/Form/VPOS/Options/index.vue
Labels: Fast Resolution, bug

#793 Add support for deploy on kubernetes
  kubernetes/configmap.yaml
  kubernetes/deployment.yaml
  kubernetes/namespace.yaml
  kubernetes/service.yaml
Labels: Continuous Integration(CI), Deployment

#791 show context menu panel right
  src/components/ADempiere/ContextMenu/contextMenuDesktop.vue
  src/components/ADempiere/DataTable/index.vue
  src/views/ADempiere/Window/index.vue
Labels: Base Changes, bug

#792 show the hide panel buttons while the table is loading
  src/components/ADempiere/DataTable/dataTables-StyleGlobal.scss
Labels: bug
