Repository adempiere/adempiere-vue, pull requests merged in 2021-07, with the labels that each got.

#961 Fix dashboard
  src/components/ADempiere/Dashboard/index.vue
  src/store/modules/ADempiere/dashboard.js
  src/views/dashboard/admin/index.vue
Labels: Fast Resolution, bug

#965 fix: This is undefined in utils methods.
  src/utils/ADempiere/valueFormat.js
Labels: Base Changes, bug

#962 feat: Add record navigation
  src/components/ADempiere/ContainerOptions/LockRecord/index.vue
  src/components/ADempiere/DefaultTable/index.vue
  src/components/ADempiere/PanelDefinition/StandardPanel.vue
  src/components/ADempiere/RecordNavigation/index.vue
  src/components/ADempiere/TabManager/index.vue
  src/router/modules/ADempiere/testRoutes.js
  src/store/modules/ADempiere/dataManager.js
  src/views/ADempiere/Test/MultiTabWindow/index.vue
  src/views/ADempiere/Test/Window/index.vue
  src/views/ADempiere/WindowView/index.vue
Labels: Medium Resolution, UI Base Features

#966 feat: Set values into panel fields
  src/components/ADempiere/DefaultTable/index.vue
  src/views/ADempiere/Test/MultiTabWindow/index.vue
  src/views/ADempiere/Test/Window/index.vue
Labels: Base Changes, UI Base Features

#968 Remove unnecessary implementation for store
  src/components/ADempiere/Field/mixin/mixinField.js
  src/store/modules/ADempiere/panel/actions.js
  src/views/ADempiere/Test/MultiTabWindow/index.vue
Labels: Base Changes

#970 Remove rounded store Vuex implementation:
  src/store/modules/ADempiere/browser.js
  src/store/modules/ADempiere/browserDefinition.js
  src/store/modules/ADempiere/dictionary/browser/actions.js
  src/store/modules/ADempiere/dictionary/browser/getters.js
  src/store/modules/ADempiere/dictionary/browser/index.js
  src/store/modules/ADempiere/dictionary/browser/mutations.js
  src/store/modules/ADempiere/dictionary/browser/state.js
  src/store/modules/ADempiere/dictionary/index.js
  src/store/modules/ADempiere/dictionary/process/actions.js
  src/store/modules/ADempiere/dictionary/process/getters.js
  src/store/modules/ADempiere/dictionary/process/index.js
  src/store/modules/ADempiere/dictionary/process/mutations.js
  src/store/modules/ADempiere/dictionary/process/state.js
  src/store/modules/ADempiere/dictionary/window/actions.js
  src/store/modules/ADempiere/dictionary/window/getters.js
  src/store/modules/ADempiere/dictionary/window/index.js
  src/store/modules/ADempiere/dictionary/window/mutations.js
  src/store/modules/ADempiere/dictionary/window/state.js
  src/store/modules/ADempiere/process/actions.js
  src/store/modules/ADempiere/process/getters.js
  src/store/modules/ADempiere/process/index.js
  src/store/modules/ADempiere/process/mutations.js
  src/store/modules/ADempiere/process/state.js
  src/store/modules/ADempiere/processDefinition.js
  src/store/modules/ADempiere/windowControl/actions.js
  src/store/modules/ADempiere/windowControl/getters.js
  src/store/modules/ADempiere/windowControl/index.js
  src/store/modules/ADempiere/windowControl/mutations.js
  src/store/modules/ADempiere/windowControl/state.js
  src/store/modules/ADempiere/windowDefinition.js
Labels: Base Changes, Fast Resolution

#973 fix: Get record notification is undefined
  src/components/ADempiere/HeaderNotification/index.vue
  src/layout/components/Navbar.vue
Labels: bug

#971 feat: Add vertical scroll default table
  src/components/ADempiere/RecordNavigation/index.vue
  src/components/ADempiere/TabManager/index.vue
Labels: Base Changes, Fast Resolution

#981 Remove duplicated series
  src/components/ADempiere/Dashboard/charts/AreaChart.vue
  src/components/ADempiere/Dashboard/charts/BarChart.vue
  src/components/ADempiere/Dashboard/charts/LineChart.vue
  src/components/ADempiere/Dashboard/charts/PieChart.vue
  src/components/ADempiere/Dashboard/charts/WaterfallChart.vue
Labels: Dashboard, bug

#977 Fix Pos
  src/components/ADempiere/Form/VPOS/Collection/fieldsListCollection.js
  src/components/ADempiere/Form/VPOS/Collection/index.vue
  src/components/ADempiere/Form/VPOS/Collection/typeCollection.vue
  src/components/ADempiere/Form/VPOS/KeyLayout/index.vue
  src/components/ADempiere/Form/VPOS/Order/fieldsListOrder.js
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/components/ADempiere/Form/VPOS/Order/line/index.vue
  src/components/ADempiere/Form/VPOS/Order/orderLineMixin.js
  src/components/ADempiere/Form/VPOS/posMixin.js
  src/layout/components/Sidebar/Item.vue
  src/store/modules/ADempiere/pointOfSales/keyLayout/actions.js
  src/store/modules/ADempiere/pointOfSales/payments/actions.js
  src/store/modules/ADempiere/pointOfSales/point/actions.js
Labels: Point of Sales (POS), bug

#979 Support Reverse Sales Transaction
  src/components/ADempiere/Form/VPOS/Options/index.vue
Labels: Point of Sales (POS), bug

#980 Correct Search Process Audit
  src/store/modules/ADempiere/processLog.js
Labels: Improve Source Code, bug

#978 Supporte Pin Point Of Sales
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/components/ADempiere/Form/VPOS/Order/line/fieldsListLine.js
  src/components/ADempiere/Form/VPOS/Order/line/index.vue
  src/components/ADempiere/Form/VPOS/posMixin.js
  src/store/modules/ADempiere/pointOfSales/getters/index.js
  src/store/modules/ADempiere/pointOfSales/point/actions.js
  src/store/modules/ADempiere/pointOfSales/point/mutations.js
  src/store/modules/ADempiere/pointOfSales/point/state.js
Labels: Fast Resolution, bug

#983 component
  docs/.vuepress/config.js
  docs/.vuepress/public/images/components/dashboard/dashboard-desktop-mobile.png
  docs/.vuepress/public/images/components/dashboard/how-to-use-it-in-the-desktop-version.gif
  docs/.vuepress/public/images/components/dashboard/how-to-use-it-in-the-mobile-version.gif
  docs/.vuepress/public/images/components/dashboard/zk-desktop-version-dashboard.png
  docs/es/guide/components/dashboard.md
  docs/guide/components/dashboard.md
  docs/zh/guide/components/dashboard.md
Labels: Dashboard, Documentation (Doc)

#984 Table browser support
  src/components/ADempiere/DefaultTable/index.vue
  src/components/ADempiere/RecordNavigation/index.vue
Labels: Base Changes, Fast Resolution

#985 Support Dashboard
  src/components/ADempiere/Dashboard/index.vue
  src/store/modules/ADempiere/dashboard.js
  src/views/dashboard/admin/index.vue
Labels: Fast Resolution, bug

#982 feat: Set uuid record with route query
  src/components/ADempiere/TabManager/index.vue
Labels: Base Changes

#986 Add support to list document type service
  src/api/ADempiere/form/point-of-sales.js
  src/components/ADempiere/Form/VPOS/Order/fieldsListOrder.js
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/components/ADempiere/Form/VPOS/posMixin.js
  src/store/modules/ADempiere/pointOfSales/getters/index.js
  src/store/modules/ADempiere/pointOfSales/point/actions.js
  src/store/modules/ADempiere/pointOfSales/point/mutations.js
  src/store/modules/ADempiere/pointOfSales/point/state.js
Labels: Base Changes, Point of Sales (POS)

#987 Switching from document type
  src/api/ADempiere/form/price-checking.js
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/components/ADempiere/Form/VPOS/posMixin.js
  src/store/modules/ADempiere/pointOfSales/order/actions.js
Labels: Fast Resolution, Point of Sales (POS), bug

#988 check-price
  docs/.vuepress/config.js
  docs/.vuepress/public/images/forms/check-price/activate-price-consultant-in-desktop-version.gif
  docs/.vuepress/public/images/forms/check-price/activate-price-consultant-in-the-mobile-version.gif
  docs/.vuepress/public/images/forms/check-price/disable-price-consultant-in-desktop-version.gif
  docs/.vuepress/public/images/forms/check-price/disable-price-consultant-in-mobile-version.gif
  docs/.vuepress/public/images/forms/check-price/ui-version-check-price.png
  docs/es/guide/forms/check-price.md
  docs/guide/forms/check-price.md
  docs/zh/guide/forms/check-price.md
Labels: Documentation (Doc)

#972 Support workflow activities
  package.json
  src/api/ADempiere/form/workflow-activity.js
  src/api/ADempiere/workflow.js
  src/components/ADempiere/Form/WorkflowActivity/fieldsList.js
  src/components/ADempiere/Form/WorkflowActivity/index.vue
  src/components/ADempiere/Form/index.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/main.js
  src/store/modules/ADempiere/WorkflowActivity.js
Labels: Proposal, Waiting for Definition

#995 guide component
  docs/.vuepress/config.js
  docs/.vuepress/public/images/components/guide/how-to-use-it-in-the-desktop-version.gif
  docs/.vuepress/public/images/components/guide/ui-version-guide.png
  docs/.vuepress/public/images/components/guide/zk-desktop-version-guide.png
  docs/es/guide/components/guide.md
  docs/guide/components/guide.md
  docs/zh/guide/components/guide.md
Labels: Documentation (Doc)

#1000 Align panel with window
  src/components/ADempiere/AuxiliaryPanel/index.vue
Labels: Base Changes

#1005 workflow and activities
  docs/.vuepress/config.js
  docs/.vuepress/public/images/components/workflows-and-activities/how-to-use-it-in-the-desktop-version.gif
  docs/.vuepress/public/images/components/workflows-and-activities/ui-version-workflows-and-activities.png
  docs/.vuepress/public/images/components/workflows-and-activities/zk-desktop-version-workflows-and-activities.png
  docs/es/guide/components/workflows-and-activities.md
  docs/guide/components/workflows-and-activities.md
  docs/zh/guide/components/workflows-and-activities.md
Labels: Documentation (Doc)

#1004 feat: Update to element-ui 2.15.3
  package.json
Labels: Update Library

#1003 fix: Tab name style.
  src/components/ADempiere/ContainerOptions/LockRecord/index.vue
Labels: UI Tools

#993 feat: Add actions menu redefinition
  src/components/ADempiere/ActionMenu/Actions.vue
  src/components/ADempiere/ActionMenu/References.vue
  src/components/ADempiere/ActionMenu/Relations.vue
  src/components/ADempiere/ActionMenu/common-style.scss
  src/components/ADempiere/ActionMenu/index.vue
  src/lang/ADempiere/en/actionMenu.js
  src/lang/ADempiere/en/index.js
  src/lang/ADempiere/es/actionMenu.js
  src/lang/ADempiere/es/index.js
  src/store/modules/ADempiere/references.js
  src/utils/ADempiere/constants/actionsMenuList.js
  src/utils/ADempiere/coreUtils.js
  src/utils/ADempiere/resource.js
  src/views/ADempiere/Test/MultiTabWindow/index.vue
  src/views/ADempiere/Window/index.vue
Labels: Base Changes, Fast Resolution

#1007 feat: Improve documentation deploy.
  .github/workflows/docs.yml
  docs/README.md
Labels: Deployment, Documentation (Doc)

#991 support Upload Excel
  src/store/modules/ADempiere/utils.js
  src/views/ADempiere/ImportExcel/index.vue
Labels: Proposal, Waiting for Definition

#1009 Fixing error when searching for product
  src/api/ADempiere/form/point-of-sales.js
  src/components/ADempiere/Field/mixin/mixinField.js
  src/components/ADempiere/Form/VPOS/Collection/convertAmount/index.vue
  src/components/ADempiere/Form/VPOS/Collection/index.vue
  src/components/ADempiere/Form/VPOS/Options/index.vue
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/components/ADempiere/Form/VPOS/ProductInfo/productList.vue
  src/components/ADempiere/Form/VPOS/posMixin.js
  src/store/modules/ADempiere/pointOfSales/getters/index.js
  src/store/modules/ADempiere/pointOfSales/point/state.js
  src/store/modules/ADempiere/pointOfSales/productPrice/actions.js
Labels: Point of Sales (POS), bug

#1010 Feat: add table header and record load by property
  src/components/ADempiere/DefaultTable/index.vue
  src/components/ADempiere/RecordNavigation/index.vue
Labels: Base Changes, UI Tools

#1011 adding full screen and table options
  src/components/ADempiere/AuxiliaryPanel/index.vue
  src/components/ADempiere/DefaultTable/columnsDisplayOption.vue
  src/components/ADempiere/DefaultTable/index.vue
  src/lang/ADempiere/en/index.js
  src/lang/ADempiere/es/index.js
  src/store/modules/ADempiere/defaultTable.js
  src/utils/ADempiere/globalMethods.js
  src/utils/ADempiere/valueUtils.js
Labels: Base Changes, UI Tools

#1013 Add packages lock for project
  .gitignore
  package-lock.json
  yarn.lock
Labels: Continuous Integration(CI)

#1014 feat: Push docker image github package registry.
  .github/workflows/docs.yml
  .github/workflows/publish.yml
  build/Dockerfile.prod
  build/start.sh
  docs/package.json
Labels: Continuous Integration(CI), Deployment

#1001 feat: Add tabs childs redefinition
  src/components/ADempiere/DefaultTable/columnsDisplayOption.vue
  src/components/ADempiere/DefaultTable/index.vue
  src/components/ADempiere/LoadingView/index.vue
  src/components/ADempiere/Tab/index.vue
  src/components/ADempiere/Tab/tabChildren.vue
  src/components/ADempiere/Tab/tabMixin.js
  src/components/ADempiere/TabManager/index.vue
  src/router/index.js
  src/styles/ADempiere/view.scss
  src/views/ADempiere/Test/MultiTabWindow/index.vue
  src/views/ADempiere/Window/StandardWindow.vue
  src/views/ADempiere/Window/index.vue
  src/views/ADempiere/Window/windowUtils.js
Labels: Base Changes, UI Tools
