Repository adempiere/adempiere-vue, pull requests merged in 2022-01, with the labels that each got.

#1461 establish the point of sale along the route
  src/store/modules/ADempiere/pointOfSales/point/actions.js
Labels: 02 Bug, 27 Fast Resolution, (POS) Point of Sales

#1463 fixe Reset Password
  src/api/ADempiere/enrollment.js
  src/components/ADempiere/Form/VPOS/Collection/index.vue
  src/permission.js
  src/views/login/forgotPassword.vue
  src/views/login/setPassword.vue
Labels: 02 Bug, 27 Fast Resolution

#1465 Add Service List Available Sellers
  src/api/ADempiere/form/point-of-sales.js
  src/components/ADempiere/Form/VPOS/Options/AssignSeller/index.vue
  src/components/ADempiere/Form/VPOS/Options/index.vue
  src/lang/ADempiere/en.js
  src/lang/ADempiere/es.js
  src/store/modules/ADempiere/pointOfSales/point/actions.js
Labels: 27 Fast Resolution, (POS) Point of Sales, 12 Feature

#1466 Fixe Enrollment
  src/api/ADempiere/enrollment.js
  src/views/login/forgotPassword.vue
  src/views/login/setPassword.vue
Labels: 02 Bug, 27 Fast Resolution

#1469 fix: Change POS.
  src/components/ADempiere/Form/VPOS/BusinessPartner/businessPartnerUpdate.vue
  src/components/ADempiere/Form/VPOS/Options/generalOptions.vue
  src/components/ADempiere/Form/VPOS/Options/index.vue
Labels: 02 Bug, 31 Medium Resolution, (POS) Point of Sales

#1482 Error adding a collect
  src/components/ADempiere/Form/VPOS/Collection/index.vue
  src/components/ADempiere/Form/VPOS/posMixin.js
Labels: 02 Bug, 27 Fast Resolution, (POS) Point of Sales

#1481 Console error when opening POS
  src/store/modules/ADempiere/WorkflowActivity.js
Labels: 02 Bug, 27 Fast Resolution, (POS) Point of Sales

#1483 Required fields
  src/components/ADempiere/Form/VPOS/OrderList/fastOrder.vue
  src/components/ADempiere/Form/VPOS/OrderList/index.vue
Labels: 02 Bug, 27 Fast Resolution, (POS) Point of Sales

#1476 Wrong symbol in Cash Withdrawal and Cash Opening
  src/components/ADempiere/Field/FieldNumber.vue
  src/components/ADempiere/Form/VPOS/Collection/index.vue
  src/components/ADempiere/Form/VPOS/Options/CashOpening/index.vue
  src/components/ADempiere/Form/VPOS/Options/Cashwithdrawal/index.vue
Labels: 02 Bug, 27 Fast Resolution, (POS) Point of Sales

#1488 fix: #1474 Disabled tabs when create record.
  src/views/ADempiere/Window/MultiTabWindow.vue
Labels: 02 Bug, (UITL) UI Tools, 31 Medium Resolution

#1486 [Bug Report] Error with re-login after timeout
  src/store/modules/user.js
Labels: 02 Bug, 27 Fast Resolution, (POS) Point of Sales

#1487 fix: Set correct boolean value.
  src/store/modules/ADempiere/dictionary/window/actions.js
  src/store/modules/ADempiere/dictionary/window/getters.js
  src/store/modules/ADempiere/panel/getters.js
  src/utils/ADempiere/contextUtils.js
  src/utils/ADempiere/dictionaryUtils.js
  src/utils/ADempiere/valueUtils.js
Labels: 02 Bug, (UILP) UI Lookups, (UITL) UI Tools, 31 Medium Resolution

#1492 fix: #1491 Read only fields.
  src/utils/ADempiere/dictionary/window.js
Labels: 02 Bug, (UILP) UI Lookups, (UITL) UI Tools, 27 Fast Resolution
