Repository adempiere/adempiere-vue, pull requests merged in 2022-04, with the labels that each got.

#1736 fix: Router link deprecated prop.
  src/layout/components/Sidebar/Link.vue
  src/layout/components/TagsView/index.vue
Labels: 02 Bug, (MEN) Menues

#1730 View PDF report
  src/components/ADempiere/FileRender/PdfFile/index.vue
Labels: 02 Bug, (UITL) UI Tools, 27 Fast Resolution, (RPT) Reports

#1732 Fixed Window: Table is very too long time to load
  src/components/ADempiere/DefaultTable/index.vue
  src/components/ADempiere/RecordNavigation/index.vue
Labels: 02 Bug, 27 Fast Resolution

#1733 Field Guide for process and Smart Browser
  src/layout/components/Navbar.vue
Labels: 02 Bug, 01 Enhancement, (UITL) UI Tools

#1734 Record Access
  src/components/ADempiere/Dialog/embedded.vue
  src/components/ADempiere/RecordAccess/recordAccess.js
  src/store/modules/ADempiere/dictionary/window/actions.js
  src/store/modules/ADempiere/recordAccess/index.js
  src/utils/ADempiere/constants/actionsMenuList.js
  src/views/ADempiere/Window/MultiTabWindow.vue
Labels: 01 Enhancement, (UITL) UI Tools, 32 Proposal

#1735 fix: Bar Chart null.
  src/components/ADempiere/Dashboard/charts/BarChart.vue
Labels: 02 Bug

#1708 Support Record Logs
  config/default.json
  src/api/ADempiere/common/resource.js
  src/api/ADempiere/user-interface/resources.js
  src/components/ADempiere/PanelInfo/Component/Attachment/index.vue
  src/components/ADempiere/PanelInfo/Component/RecordLogs/index.vue
  src/components/ADempiere/PanelInfo/index.vue
  src/components/ADempiere/TabManager/index.vue
  src/components/ADempiere/recordLogs/index.vue
  src/lang/ADempiere/en/window.js
  src/lang/ADempiere/es/window.js
  src/store/modules/ADempiere/containerInfo.js
  src/store/modules/ADempiere/containerInfo/index.js
  src/store/modules/ADempiere/utils.js
  src/utils/ADempiere/globalMethods.js
  src/utils/ADempiere/resource.js
  src/utils/ADempiere/valueUtils.js
  src/views/ADempiere/Window/MultiTabWindow.vue
  src/views/ADempiere/Window/index.vue
Labels: 01 Enhancement, (UITL) UI Tools, 32 Proposal

#1745 Double request at the window
  src/layout/components/Navbar.vue
Labels: 02 Bug, 27 Fast Resolution

#1747 fix: Default value in lookup field.
  src/components/ADempiere/Field/FieldOptions/ContextInfo/index.vue
  src/components/ADempiere/Field/mixin/mixinFieldSelect.js
  src/lang/ADempiere/en/index.js
  src/lang/ADempiere/es/index.js
Labels: 02 Bug, (UILP) UI Lookups

#1749 Change price list at the point of sale
  src/components/ADempiere/Form/VPOS/Order/index.vue
  src/store/modules/ADempiere/pointOfSales/order/actions.js
Labels: 02 Bug, 27 Fast Resolution, (POS) Point of Sales

#1748 feat: Refactor props components fields.
  src/components/ADempiere/Field/FieldAutocomplete.vue
  src/components/ADempiere/Field/FieldBinary.vue
  src/components/ADempiere/Field/FieldButton.vue
  src/components/ADempiere/Field/FieldColor.vue
  src/components/ADempiere/Field/FieldDate.vue
  src/components/ADempiere/Field/FieldImage.vue
  src/components/ADempiere/Field/FieldLocator.vue
  src/components/ADempiere/Field/FieldNumber.vue
  src/components/ADempiere/Field/FieldSelect.vue
  src/components/ADempiere/Field/FieldSelectMultiple.vue
  src/components/ADempiere/Field/FieldText.vue
  src/components/ADempiere/Field/FieldTextLong.vue
  src/components/ADempiere/Field/FieldTime.vue
  src/components/ADempiere/Field/FieldYesNo.vue
  src/components/ADempiere/Field/mixin/mixinField.js
  src/lang/ADempiere/en/index.js
  src/lang/ADempiere/es/index.js
Labels: 01 Enhancement, (UILP) UI Lookups, 20 Refactoring

#1750 Reload When Role Changes
  src/store/modules/user.js
  src/views/profile/components/RolesNavbar.vue
Labels: 02 Bug, 27 Fast Resolution

#1751 Fixed Screenfull
  src/components/Screenfull/index.vue
Labels: 02 Bug, 27 Fast Resolution

#1752 fix: Search duplicated request.
  src/components/ADempiere/AuxiliaryPanel/index.vue
  src/components/ADempiere/DefaultTable/index.vue
  src/components/ADempiere/RecordNavigation/index.vue
  src/views/ADempiere/Window/StandardWindow.vue
  src/views/ADempiere/Window/index.vue
Labels: 02 Bug, (UITL) UI Tools

#1755 feat: #56 Add url field.
  src/components/ADempiere/Field/FieldUrl.vue
  src/components/ADempiere/Field/index.vue
  src/utils/ADempiere/dataUtils.js
  src/utils/ADempiere/dictionaryUtils.js
  src/utils/ADempiere/references.js
  src/utils/ADempiere/valueUtils.js
Labels: 31 Medium Resolution

#1753 fix: #1590 Run process with empty mandatory fields
  src/store/modules/ADempiere/dictionary/process/actions.js
  src/store/modules/ADempiere/dictionary/process/getters.js
  src/store/modules/ADempiere/dictionary/report/actions.js
  src/store/modules/ADempiere/dictionary/report/getters.js
  src/store/modules/ADempiere/processManager.js
  src/store/modules/ADempiere/reportManager.js
  src/utils/ADempiere/dictionary/process.js
  src/utils/ADempiere/dictionary/report.js
Labels: 02 Bug, 31 Medium Resolution, (PRC) Processes, (RPT) Reports

#1760 feat: Add support to search value in lookup field
  src/components/ADempiere/Field/FieldAutocomplete.vue
  src/components/ADempiere/Field/FieldSelect.vue
  src/components/ADempiere/Field/mixin/mixinFieldSelect.js
  src/store/modules/ADempiere/data/actions.js
  src/store/modules/ADempiere/lookupManager.js
  src/store/modules/ADempiere/panel/getters.js
  src/views/ADempiere/Browser/index.vue
  src/views/ADempiere/Process/mixinProcess.js
  src/views/ADempiere/Report/mixinReport.js
  src/views/ADempiere/Window/index.vue
Labels: 01 Enhancement, (UILP) UI Lookups, 31 Medium Resolution
